$axure.loadCurrentPage({
  "url":"添加课程.html",
  "generationDate":new Date(1528362642515.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2564aa4fe6d4494e973ecc8f44b83079",
    "type":"Axure:Page",
    "name":"添加课程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ab3c36609fa840a49c4660796d45e3d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":74},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c12ddc3806bc45e49b3c7c8f1dd52294",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":74},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3fce0e08ba14a82aa50a4918d6a9b47",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":124},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84a8799e99834891b0ce38f4989c9073",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":124},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c0a7e7a511842f99cc1164aa2c4fde6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":180},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ea0254bd70c4902b16d9ddc36b4d4da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":180},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"195ee4a6680f40e5ac60529b882c8a95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":240},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d07da94ec3d4d5b807bc9d5f59f0cbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":240},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c58af42658b445f1b71d855b4349f81e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":310},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"530cde8ec5af4bce80574c4ea1bdd5f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":310},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08eeeb80f2454fc1a6fafe44daf521fa",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":307},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c7771db9a9c449dda9c1f210e7a9d0a9",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":240},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"16369ab03c804aad8b55976f368b173c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":178},
            "size":{
              "width":120,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a42bc1642ba4ba0824cf8569a7cf748",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":178},
                "size":{
                  "width":120,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加课程/u12.png"}},
{
          "id":"19082d84d20b47dcad7a57043503cd2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":124},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20d942af949b4c74a5faa11bf6734a26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":124},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加课程/u14.png"}},
{
          "id":"cea0af030d394c28910b33907950c1c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":74},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14f27dbb31ee4e5b9d2e74fa4c9ed59d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":74},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加课程/u14.png"}},
{
          "id":"df23f2e1aede4df3a639127396f3f82f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":250,
              "y":240},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f861f39babb7412fa779f5ee6ce63ced",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":250,
                  "y":240},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加课程/u18.png"}},
{
          "id":"66b5a422cd714e91ad80ce044674804c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":255,
              "y":310},
            "size":{
              "width":185,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb02d1adf87d45e1a790a8e2b5a2c339",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":255,
                  "y":310},
                "size":{
                  "width":185,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加课程/u20.png"}},
{
          "id":"7068f5e3df864848aa78bbd885fc0ff8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":375},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4322e57b72ce47fe915d5faab1c07ede",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":375},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6657645e7fc74e8bb1b67ee6dc6c269e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":230,
              "y":390},
            "size":{
              "width":170,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb517b79c15d4fe08f72230350401b4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":230,
                  "y":390},
                "size":{
                  "width":170,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加课程/u24.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ab3c36609fa840a49c4660796d45e3d0":{
      "scriptId":"u0"},
    "c12ddc3806bc45e49b3c7c8f1dd52294":{
      "scriptId":"u1"},
    "e3fce0e08ba14a82aa50a4918d6a9b47":{
      "scriptId":"u2"},
    "84a8799e99834891b0ce38f4989c9073":{
      "scriptId":"u3"},
    "3c0a7e7a511842f99cc1164aa2c4fde6":{
      "scriptId":"u4"},
    "7ea0254bd70c4902b16d9ddc36b4d4da":{
      "scriptId":"u5"},
    "195ee4a6680f40e5ac60529b882c8a95":{
      "scriptId":"u6"},
    "3d07da94ec3d4d5b807bc9d5f59f0cbe":{
      "scriptId":"u7"},
    "c58af42658b445f1b71d855b4349f81e":{
      "scriptId":"u8"},
    "530cde8ec5af4bce80574c4ea1bdd5f3":{
      "scriptId":"u9"},
    "08eeeb80f2454fc1a6fafe44daf521fa":{
      "scriptId":"u10"},
    "c7771db9a9c449dda9c1f210e7a9d0a9":{
      "scriptId":"u11"},
    "16369ab03c804aad8b55976f368b173c":{
      "scriptId":"u12"},
    "6a42bc1642ba4ba0824cf8569a7cf748":{
      "scriptId":"u13"},
    "19082d84d20b47dcad7a57043503cd2d":{
      "scriptId":"u14"},
    "20d942af949b4c74a5faa11bf6734a26":{
      "scriptId":"u15"},
    "cea0af030d394c28910b33907950c1c5":{
      "scriptId":"u16"},
    "14f27dbb31ee4e5b9d2e74fa4c9ed59d":{
      "scriptId":"u17"},
    "df23f2e1aede4df3a639127396f3f82f":{
      "scriptId":"u18"},
    "f861f39babb7412fa779f5ee6ce63ced":{
      "scriptId":"u19"},
    "66b5a422cd714e91ad80ce044674804c":{
      "scriptId":"u20"},
    "eb02d1adf87d45e1a790a8e2b5a2c339":{
      "scriptId":"u21"},
    "7068f5e3df864848aa78bbd885fc0ff8":{
      "scriptId":"u22"},
    "4322e57b72ce47fe915d5faab1c07ede":{
      "scriptId":"u23"},
    "6657645e7fc74e8bb1b67ee6dc6c269e":{
      "scriptId":"u24"},
    "fb517b79c15d4fe08f72230350401b4b":{
      "scriptId":"u25"}}});