$axure.loadCurrentPage({
  "url":"查看用户信息.html",
  "generationDate":new Date(1528362643926.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"695aff3164e143baab4aa8fe4dcebe24",
    "type":"Axure:Page",
    "name":"查看用户信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"24bb22572a1d4736856831c85e7bc64c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":79},
            "size":{
              "width":290,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"183ba56b4fbd42acb5d7c03fa2afbe6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":79},
                "size":{
                  "width":290,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看用户信息/u0.png"}},
{
          "id":"e7db9fff76b549358d8c18263a2e7477",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":130},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8bcd4e5cbbe43dcb946b0c514dc9f9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":130},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19c5ec1cd1b24846a025dea4bfee3826",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":130},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"557dce54d9cb40ceac6f7775a90ac23c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":130},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加课程实验/u32.png"}},
{
          "id":"c6bd9f09fb9f4c5295b301a1520138fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":162},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ca2ddc9962e42d3a1345b9fd2789466",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":162},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7264d4be2331481b9e8814d68b7e9a4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":162},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edb48e0d2c8c4662a79c04ff119f0f75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":162},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加课程实验/u32.png"}},
{
          "id":"c00d1f953eb44517b4d3a2bddcc850eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":191},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"201d8bc853624a6595c06b3b3a63eb22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":191},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7acf61f1961043c8a9a5f97da96f15eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":191},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0730671bfa5e432996c71626f4582819",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":191},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加课程实验/u32.png"}},
{
          "id":"414b1ba068d14c9d87e6ca832b3cd25c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":222},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80aaaa8db8d146f09b0641dabbec67ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":222},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f49297a128d240e4b1858a5a6b2936d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":222},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c54fd57528604692a2ec6bf49fd78385",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":222},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加课程实验/u32.png"}},
{
          "id":"4df4e8f188b24c5a8cc2d90aff624bfa",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":265},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2b6f0b2c49a740cf8a1c23b83ff6b4df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":422,
              "y":138},
            "size":{
              "width":128,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"611dbf4d6c4b46b2a6659267b56a6ee9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":422,
                  "y":138},
                "size":{
                  "width":128,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看用户信息/u19.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "24bb22572a1d4736856831c85e7bc64c":{
      "scriptId":"u0"},
    "183ba56b4fbd42acb5d7c03fa2afbe6d":{
      "scriptId":"u1"},
    "e7db9fff76b549358d8c18263a2e7477":{
      "scriptId":"u2"},
    "a8bcd4e5cbbe43dcb946b0c514dc9f9b":{
      "scriptId":"u3"},
    "19c5ec1cd1b24846a025dea4bfee3826":{
      "scriptId":"u4"},
    "557dce54d9cb40ceac6f7775a90ac23c":{
      "scriptId":"u5"},
    "c6bd9f09fb9f4c5295b301a1520138fb":{
      "scriptId":"u6"},
    "0ca2ddc9962e42d3a1345b9fd2789466":{
      "scriptId":"u7"},
    "7264d4be2331481b9e8814d68b7e9a4e":{
      "scriptId":"u8"},
    "edb48e0d2c8c4662a79c04ff119f0f75":{
      "scriptId":"u9"},
    "c00d1f953eb44517b4d3a2bddcc850eb":{
      "scriptId":"u10"},
    "201d8bc853624a6595c06b3b3a63eb22":{
      "scriptId":"u11"},
    "7acf61f1961043c8a9a5f97da96f15eb":{
      "scriptId":"u12"},
    "0730671bfa5e432996c71626f4582819":{
      "scriptId":"u13"},
    "414b1ba068d14c9d87e6ca832b3cd25c":{
      "scriptId":"u14"},
    "80aaaa8db8d146f09b0641dabbec67ef":{
      "scriptId":"u15"},
    "f49297a128d240e4b1858a5a6b2936d4":{
      "scriptId":"u16"},
    "c54fd57528604692a2ec6bf49fd78385":{
      "scriptId":"u17"},
    "4df4e8f188b24c5a8cc2d90aff624bfa":{
      "scriptId":"u18"},
    "2b6f0b2c49a740cf8a1c23b83ff6b4df":{
      "scriptId":"u19"},
    "611dbf4d6c4b46b2a6659267b56a6ee9":{
      "scriptId":"u20"}}});