$axure.loadCurrentPage({
  "url":"学生列表.html",
  "generationDate":new Date(1528362642146.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"56915aef6e2a403dbe2b91976ca4b046",
    "type":"Axure:Page",
    "name":"学生列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5af7482099e14fa084996ff5a9ca246d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":40,
              "y":196},
            "size":{
              "width":780,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b20518d9d5d046788afd15dd1e0fbb9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":40,
                  "y":196},
                "size":{
                  "width":780,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u0.png"}},
{
          "id":"734666d5a28043aebba49e0f4c1a9626",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":203},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e32371aeaf74b89a1b347a4cb4bf80a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":203},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db3eb65e6c55421680ff940de6b35b0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":311,
              "y":203},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"209fa9837a4d42509bd8eac659c94bbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":311,
                  "y":203},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u4.png"}},
{
          "id":"7395df7b858b4f4dbb23a53f9c30f77e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":203},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db604cc2413444dbb487abc141272f2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":203},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d9d9ec2b61b44f1b299025d1f82e99c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":513,
              "y":203},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5f861cda85640da9ab6f7726d467b98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":513,
                  "y":203},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u8.png"}},
{
          "id":"0045788e72c24736b0e49c6d9568c368",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":203},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c2db971512949c6bd9d2430d0388c9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":203},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7cee2946b7894ef6bfdb6fc57586c4bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":120,
              "y":203},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0391b0a1dde34a2ca499a2f47d3f0196",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":120,
                  "y":203},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u12.png"}},
{
          "id":"804c0905c7264d34ae4eb1a59c9fc4c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":730,
              "y":203},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08837870a947457592c01d7d94a4db98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":730,
                  "y":203},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0ada1b279c1543d0bc83522e381154a3",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 链接",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/学生列表/u14.png"}},
{
          "id":"a60cd1e4d5d9430484f886bf02fdc4f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":40,
              "y":226},
            "size":{
              "width":780,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93f319534fe14506a8f43a2306a68f4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":40,
                  "y":226},
                "size":{
                  "width":780,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u0.png"}},
{
          "id":"5c8dca2e665f443c828908d9d14db947",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":233},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"427627c61d664f9294eb0c337ef75002",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":233},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3370d9eb017d44e897841bb52609c8be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":311,
              "y":233},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95742ab0b21548af8f3e66cd1b6bf327",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":311,
                  "y":233},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u4.png"}},
{
          "id":"18e5cd45741a4d81ae6d6c433c56bb62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":233},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc6f17f38151449dad0a7c99081d5e59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":233},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d84a270d96ed4db493554d14e79b8c02",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":513,
              "y":233},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca2084b9c0f04ea8aba5e3e626368239",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":513,
                  "y":233},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u8.png"}},
{
          "id":"c04ac8d4d8bb40e088db946ce85e5b42",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":233},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb5058edd753434c9d29aba76271fe0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":233},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e947a8b146c4bc089dd8e6488a58b8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":120,
              "y":233},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3800bdc09e4484f9186c91d48ca8bfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":120,
                  "y":233},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u12.png"}},
{
          "id":"e6be28e80a8c4db294182ee72e6358ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":730,
              "y":233},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d86e3cf5105a456080e814a134082e33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":730,
                  "y":233},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cbe5f46061104a29951b035992b24d46",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 链接",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/学生列表/u14.png"}},
{
          "id":"2decbcc9587c4086b47f3f6a8d87b697",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":40,
              "y":256},
            "size":{
              "width":780,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c49c18e0f0c48168c3d99d59720377d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":40,
                  "y":256},
                "size":{
                  "width":780,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u0.png"}},
{
          "id":"08434e18ea0f49a8b1f1a9c7a503b8e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":263},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ec3d1a303f0408fb6752fed90994c3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":263},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78eea0da29c940fd8f3ea9ffc4d199a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":311,
              "y":263},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b5e9583b9bf46eeb9cc388621a3fd2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":311,
                  "y":263},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u4.png"}},
{
          "id":"501de32278c44cc09ad082086175754a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":263},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e95b5d900da4e6580b9a91c4020e18a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":263},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a5f2e37dcaf436f8c51ee20e90d3679",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":513,
              "y":263},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e78ecdb2c68142d59a5bc5be33455b14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":513,
                  "y":263},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u8.png"}},
{
          "id":"0574acda2a1e4adb9b150d2bb1211022",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":263},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b958009825f44c19bc9a73120be2bc6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":263},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20cd21d097544ffbadd6587d8bb6fb24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":120,
              "y":263},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a83d8fbeb234715bd271340e79a720b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":120,
                  "y":263},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u12.png"}},
{
          "id":"2b7c46b3e9fd4a56ba688cb1ef975250",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":730,
              "y":263},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"488d9e73f70e4bc3a8b4400348ad0fa8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":730,
                  "y":263},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"40f9df212ea94602b81b1ea68e5dc41e",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 链接",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/学生列表/u14.png"}},
{
          "id":"d23babbf927e4182abb8c4cbb7ac5cf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":40,
              "y":70},
            "size":{
              "width":780,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"125ef3537cfe40fa943985f95c5124f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":40,
                  "y":70},
                "size":{
                  "width":780,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u0.png"}},
{
          "id":"a370b8f1fa4d47c0b6987485284114cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":77},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66171190059e447f8423660b738456a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":77},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"374ecf6acb254fa4bbae117ddebdf108",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":311,
              "y":77},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"451d5f24360a4c75815f5ae3395d43c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":311,
                  "y":77},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u4.png"}},
{
          "id":"d2da9363cd5b4e33bf878b4ee1b1031c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":77},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ecf9c8bfe1a4cf4b0b071bb0afc807c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":77},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc63e814f1ff45cd9c3f30c575c65d2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":513,
              "y":77},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7b2b007bdd04d3e90bf14cfda665ced",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":513,
                  "y":77},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u8.png"}},
{
          "id":"d8453b9b533c44c082c3c52d0297a184",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":77},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7016af27df8b45a989b99091f18aebd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":77},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf554d1636104988b617d979d6ed0581",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":120,
              "y":77},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"505f054359864a52ac53d9a2c2a0d9d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":120,
                  "y":77},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u12.png"}},
{
          "id":"8fcffa7a92e649bd8da448b9bcb241fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":730,
              "y":77},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c286d3e2b97401083f8ca0acf5c0e2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":730,
                  "y":77},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u14.png"}},
{
          "id":"f9036f36417f4edd9649cfd8ba9c337b",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":100},
            "size":{
              "width":780,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c083f289454d425195842e4047652d35",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"07e6b2a9838548a8b06a28c4d0a7654c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u15.png"}},
{
              "id":"43ce4a15d6784d61bbd0f0f4f6efd6fa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"554cfca922ff41d983669ac41a0a0869",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"7bf2761b6dd14221a32e259f47494b20",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"56e0fe0e5a0e44f9b551b4648aed528c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"4dbf5ff066764da99d5daa252e9db433",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2703ce798ef04c4aa7ccf4cf33e038dc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u15.png"}},
{
              "id":"13d6952256784ecdade76a4d311244b2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"60e13d73d41d415b95307d80309ad46a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"ce1be341aae74604821ebd5b3f075bd5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fe8f24adc69f434ca61237c58e84f9f5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"e8566ee19bd740949b36ca33a1bc1952",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fc201b41ff3c424383f5b00e61bc2fd1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u15.png"}},
{
              "id":"71f35e5a186b4b3aacb6fb4d41bc16ae",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f375768505244b2997276e6247380370",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"8b7b7134d756419e845ec1fa541c364f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5d3699d656344277b032e74d70f98e75",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"94641c37c7944f669fe4e7fbb6703b5f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":119,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f98d4d1007f54b789056d8ffe5f65152",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":119,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u74.png"}},
{
              "id":"884fa0e4bdc34a32bd42ea827a611c68",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":36},
                "size":{
                  "width":119,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"31dd92961d8d4a16a28136a5259e386a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":36},
                    "size":{
                      "width":119,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u88.png"}},
{
              "id":"2113ef1f254d4efbbb4c3ecbb45bf1f6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":66},
                "size":{
                  "width":119,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"993a99d2c9d6408bb38d40a7ff9924c8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":66},
                    "size":{
                      "width":119,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u103.png"}},
{
              "id":"1ef10cb3eca7406594eff86ebc2b4420",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":555,
                  "y":0},
                "size":{
                  "width":117,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"92077d3d3b8d43d99df20cd99187cbab",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":555,
                      "y":0},
                    "size":{
                      "width":117,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u78.png"}},
{
              "id":"bf2a7f2d5f234da285e0a64289c2adac",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":555,
                  "y":36},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e694f7c269424d50b9acc8f0670c8746",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":555,
                      "y":36},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u92.png"}},
{
              "id":"7d30176b3fed428e9e1368ef23c7dfc7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":555,
                  "y":66},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3577274f4edc4e7ea55448e6d0a4d14f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":555,
                      "y":66},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u107.png"}},
{
              "id":"3abc441ae93d4334a19ad26a0afceed9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":419,
                  "y":0},
                "size":{
                  "width":136,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"57b71599ca1f4dcfa99bff7c4b3c511f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":419,
                      "y":0},
                    "size":{
                      "width":136,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u76.png"}},
{
              "id":"b8ad43a60ba94cb6b29c0b1f134bb08d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":419,
                  "y":36},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e90ed5b82356474c953780f1ebe5f5d8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":419,
                      "y":36},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u90.png"}},
{
              "id":"eb5863f606a24bc0aa606af41a51da14",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":419,
                  "y":66},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6d95bb13c0744193963c5116c6f2d569",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":419,
                      "y":66},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u105.png"}},
{
              "id":"eb8317d0521a402c8093e3d2c305f819",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":672,
                  "y":0},
                "size":{
                  "width":108,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7ca4ecfb3fd74364930dc5b673439241",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":672,
                      "y":0},
                    "size":{
                      "width":108,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u80.png"}},
{
              "id":"1806a9cb1a234b61b2d591154b938759",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":672,
                  "y":36},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3c84d00a60594421a1dc958f9df6c978",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":672,
                      "y":36},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8af368bd9f4e456fa8dd58dd4378eefe",
                      "label":"",
                      "type":"hyperlink",
                      "styleType":"hyperlink",
                      "visible":true,
                      "style":{
},
                      "adaptiveStyles":{
},
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 批改成绩",
                                  "target":{
                                    "targetType":"page",
                                    "url":"批改成绩.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true}]}],
              "images":{
                "normal~":"images/学生列表/u94.png"}},
{
              "id":"6842698d8eea45abbe9f42f19915bb04",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":672,
                  "y":66},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9650c4a77fa0401699797719925b0f8f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":672,
                      "y":66},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1aea93df88f14bfc83bcb954ba2d359f",
                      "label":"",
                      "type":"hyperlink",
                      "styleType":"hyperlink",
                      "visible":true,
                      "style":{
},
                      "adaptiveStyles":{
},
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 批改成绩",
                                  "target":{
                                    "targetType":"page",
                                    "url":"批改成绩.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true}]}],
              "images":{
                "normal~":"images/学生列表/u109.png"}}]},
{
          "id":"0a7f232f47c642d1947b9d4b6696726f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":860,
              "y":119},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2de55d3c0c8a44b59506a1a9c211c4ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":860,
                  "y":119},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u112.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5af7482099e14fa084996ff5a9ca246d":{
      "scriptId":"u0"},
    "b20518d9d5d046788afd15dd1e0fbb9e":{
      "scriptId":"u1"},
    "734666d5a28043aebba49e0f4c1a9626":{
      "scriptId":"u2"},
    "9e32371aeaf74b89a1b347a4cb4bf80a":{
      "scriptId":"u3"},
    "db3eb65e6c55421680ff940de6b35b0e":{
      "scriptId":"u4"},
    "209fa9837a4d42509bd8eac659c94bbe":{
      "scriptId":"u5"},
    "7395df7b858b4f4dbb23a53f9c30f77e":{
      "scriptId":"u6"},
    "db604cc2413444dbb487abc141272f2f":{
      "scriptId":"u7"},
    "5d9d9ec2b61b44f1b299025d1f82e99c":{
      "scriptId":"u8"},
    "d5f861cda85640da9ab6f7726d467b98":{
      "scriptId":"u9"},
    "0045788e72c24736b0e49c6d9568c368":{
      "scriptId":"u10"},
    "8c2db971512949c6bd9d2430d0388c9d":{
      "scriptId":"u11"},
    "7cee2946b7894ef6bfdb6fc57586c4bb":{
      "scriptId":"u12"},
    "0391b0a1dde34a2ca499a2f47d3f0196":{
      "scriptId":"u13"},
    "804c0905c7264d34ae4eb1a59c9fc4c1":{
      "scriptId":"u14"},
    "08837870a947457592c01d7d94a4db98":{
      "scriptId":"u15"},
    "0ada1b279c1543d0bc83522e381154a3":{
      "scriptId":"u16"},
    "a60cd1e4d5d9430484f886bf02fdc4f1":{
      "scriptId":"u17"},
    "93f319534fe14506a8f43a2306a68f4c":{
      "scriptId":"u18"},
    "5c8dca2e665f443c828908d9d14db947":{
      "scriptId":"u19"},
    "427627c61d664f9294eb0c337ef75002":{
      "scriptId":"u20"},
    "3370d9eb017d44e897841bb52609c8be":{
      "scriptId":"u21"},
    "95742ab0b21548af8f3e66cd1b6bf327":{
      "scriptId":"u22"},
    "18e5cd45741a4d81ae6d6c433c56bb62":{
      "scriptId":"u23"},
    "fc6f17f38151449dad0a7c99081d5e59":{
      "scriptId":"u24"},
    "d84a270d96ed4db493554d14e79b8c02":{
      "scriptId":"u25"},
    "ca2084b9c0f04ea8aba5e3e626368239":{
      "scriptId":"u26"},
    "c04ac8d4d8bb40e088db946ce85e5b42":{
      "scriptId":"u27"},
    "bb5058edd753434c9d29aba76271fe0a":{
      "scriptId":"u28"},
    "7e947a8b146c4bc089dd8e6488a58b8f":{
      "scriptId":"u29"},
    "c3800bdc09e4484f9186c91d48ca8bfd":{
      "scriptId":"u30"},
    "e6be28e80a8c4db294182ee72e6358ed":{
      "scriptId":"u31"},
    "d86e3cf5105a456080e814a134082e33":{
      "scriptId":"u32"},
    "cbe5f46061104a29951b035992b24d46":{
      "scriptId":"u33"},
    "2decbcc9587c4086b47f3f6a8d87b697":{
      "scriptId":"u34"},
    "0c49c18e0f0c48168c3d99d59720377d":{
      "scriptId":"u35"},
    "08434e18ea0f49a8b1f1a9c7a503b8e7":{
      "scriptId":"u36"},
    "7ec3d1a303f0408fb6752fed90994c3a":{
      "scriptId":"u37"},
    "78eea0da29c940fd8f3ea9ffc4d199a0":{
      "scriptId":"u38"},
    "7b5e9583b9bf46eeb9cc388621a3fd2f":{
      "scriptId":"u39"},
    "501de32278c44cc09ad082086175754a":{
      "scriptId":"u40"},
    "9e95b5d900da4e6580b9a91c4020e18a":{
      "scriptId":"u41"},
    "2a5f2e37dcaf436f8c51ee20e90d3679":{
      "scriptId":"u42"},
    "e78ecdb2c68142d59a5bc5be33455b14":{
      "scriptId":"u43"},
    "0574acda2a1e4adb9b150d2bb1211022":{
      "scriptId":"u44"},
    "b958009825f44c19bc9a73120be2bc6d":{
      "scriptId":"u45"},
    "20cd21d097544ffbadd6587d8bb6fb24":{
      "scriptId":"u46"},
    "3a83d8fbeb234715bd271340e79a720b":{
      "scriptId":"u47"},
    "2b7c46b3e9fd4a56ba688cb1ef975250":{
      "scriptId":"u48"},
    "488d9e73f70e4bc3a8b4400348ad0fa8":{
      "scriptId":"u49"},
    "40f9df212ea94602b81b1ea68e5dc41e":{
      "scriptId":"u50"},
    "d23babbf927e4182abb8c4cbb7ac5cf4":{
      "scriptId":"u51"},
    "125ef3537cfe40fa943985f95c5124f1":{
      "scriptId":"u52"},
    "a370b8f1fa4d47c0b6987485284114cd":{
      "scriptId":"u53"},
    "66171190059e447f8423660b738456a5":{
      "scriptId":"u54"},
    "374ecf6acb254fa4bbae117ddebdf108":{
      "scriptId":"u55"},
    "451d5f24360a4c75815f5ae3395d43c4":{
      "scriptId":"u56"},
    "d2da9363cd5b4e33bf878b4ee1b1031c":{
      "scriptId":"u57"},
    "3ecf9c8bfe1a4cf4b0b071bb0afc807c":{
      "scriptId":"u58"},
    "cc63e814f1ff45cd9c3f30c575c65d2a":{
      "scriptId":"u59"},
    "a7b2b007bdd04d3e90bf14cfda665ced":{
      "scriptId":"u60"},
    "d8453b9b533c44c082c3c52d0297a184":{
      "scriptId":"u61"},
    "7016af27df8b45a989b99091f18aebd1":{
      "scriptId":"u62"},
    "bf554d1636104988b617d979d6ed0581":{
      "scriptId":"u63"},
    "505f054359864a52ac53d9a2c2a0d9d4":{
      "scriptId":"u64"},
    "8fcffa7a92e649bd8da448b9bcb241fd":{
      "scriptId":"u65"},
    "4c286d3e2b97401083f8ca0acf5c0e2d":{
      "scriptId":"u66"},
    "f9036f36417f4edd9649cfd8ba9c337b":{
      "scriptId":"u67"},
    "c083f289454d425195842e4047652d35":{
      "scriptId":"u68"},
    "07e6b2a9838548a8b06a28c4d0a7654c":{
      "scriptId":"u69"},
    "4dbf5ff066764da99d5daa252e9db433":{
      "scriptId":"u70"},
    "2703ce798ef04c4aa7ccf4cf33e038dc":{
      "scriptId":"u71"},
    "e8566ee19bd740949b36ca33a1bc1952":{
      "scriptId":"u72"},
    "fc201b41ff3c424383f5b00e61bc2fd1":{
      "scriptId":"u73"},
    "94641c37c7944f669fe4e7fbb6703b5f":{
      "scriptId":"u74"},
    "f98d4d1007f54b789056d8ffe5f65152":{
      "scriptId":"u75"},
    "3abc441ae93d4334a19ad26a0afceed9":{
      "scriptId":"u76"},
    "57b71599ca1f4dcfa99bff7c4b3c511f":{
      "scriptId":"u77"},
    "1ef10cb3eca7406594eff86ebc2b4420":{
      "scriptId":"u78"},
    "92077d3d3b8d43d99df20cd99187cbab":{
      "scriptId":"u79"},
    "eb8317d0521a402c8093e3d2c305f819":{
      "scriptId":"u80"},
    "7ca4ecfb3fd74364930dc5b673439241":{
      "scriptId":"u81"},
    "43ce4a15d6784d61bbd0f0f4f6efd6fa":{
      "scriptId":"u82"},
    "554cfca922ff41d983669ac41a0a0869":{
      "scriptId":"u83"},
    "13d6952256784ecdade76a4d311244b2":{
      "scriptId":"u84"},
    "60e13d73d41d415b95307d80309ad46a":{
      "scriptId":"u85"},
    "71f35e5a186b4b3aacb6fb4d41bc16ae":{
      "scriptId":"u86"},
    "f375768505244b2997276e6247380370":{
      "scriptId":"u87"},
    "884fa0e4bdc34a32bd42ea827a611c68":{
      "scriptId":"u88"},
    "31dd92961d8d4a16a28136a5259e386a":{
      "scriptId":"u89"},
    "b8ad43a60ba94cb6b29c0b1f134bb08d":{
      "scriptId":"u90"},
    "e90ed5b82356474c953780f1ebe5f5d8":{
      "scriptId":"u91"},
    "bf2a7f2d5f234da285e0a64289c2adac":{
      "scriptId":"u92"},
    "e694f7c269424d50b9acc8f0670c8746":{
      "scriptId":"u93"},
    "1806a9cb1a234b61b2d591154b938759":{
      "scriptId":"u94"},
    "3c84d00a60594421a1dc958f9df6c978":{
      "scriptId":"u95"},
    "8af368bd9f4e456fa8dd58dd4378eefe":{
      "scriptId":"u96"},
    "7bf2761b6dd14221a32e259f47494b20":{
      "scriptId":"u97"},
    "56e0fe0e5a0e44f9b551b4648aed528c":{
      "scriptId":"u98"},
    "ce1be341aae74604821ebd5b3f075bd5":{
      "scriptId":"u99"},
    "fe8f24adc69f434ca61237c58e84f9f5":{
      "scriptId":"u100"},
    "8b7b7134d756419e845ec1fa541c364f":{
      "scriptId":"u101"},
    "5d3699d656344277b032e74d70f98e75":{
      "scriptId":"u102"},
    "2113ef1f254d4efbbb4c3ecbb45bf1f6":{
      "scriptId":"u103"},
    "993a99d2c9d6408bb38d40a7ff9924c8":{
      "scriptId":"u104"},
    "eb5863f606a24bc0aa606af41a51da14":{
      "scriptId":"u105"},
    "6d95bb13c0744193963c5116c6f2d569":{
      "scriptId":"u106"},
    "7d30176b3fed428e9e1368ef23c7dfc7":{
      "scriptId":"u107"},
    "3577274f4edc4e7ea55448e6d0a4d14f":{
      "scriptId":"u108"},
    "6842698d8eea45abbe9f42f19915bb04":{
      "scriptId":"u109"},
    "9650c4a77fa0401699797719925b0f8f":{
      "scriptId":"u110"},
    "1aea93df88f14bfc83bcb954ba2d359f":{
      "scriptId":"u111"},
    "0a7f232f47c642d1947b9d4b6696726f":{
      "scriptId":"u112"},
    "2de55d3c0c8a44b59506a1a9c211c4ee":{
      "scriptId":"u113"}}});