$axure.loadCurrentPage({
  "url":"添加课程实验.html",
  "generationDate":new Date(1528362643038.81),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3a77dbc919274626a2d524cb64475df4",
    "type":"Axure:Page",
    "name":"添加课程实验",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b7964d83ed7949d9acf07213a545fd69",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":290},
            "size":{
              "width":300,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c5f86c9db904b9fae92284aaeab1867",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7304dbcc4642457997a6e94589b9725a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"925d837a650142fc86aa9ea31ba20c80",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d811155171a0406089b6cbc82aaaff97",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"d701dc9099a84a458bec3323c5b1d7bf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5e4d7c9dfe71408eb85ce6c99143efbd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"550827dd2a944a9f89d2caf8469ae6c1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f11b3fee620e46058bbaf991719053a7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"9da0d011531b4539b8407e16c34e3ddf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"24701ee53b194ae2ba7fe81d5e00042b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"3a1b4cc4339a4b2c86dd51b15e55b653",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d781a802f39849cc967b5a82e8992393",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"1581ff3528394a3886aa7e57c936f075",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"26da75ffdc124847b816a24d285a6b9d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u12.png"}},
{
              "id":"ff71d7baee4045ef8db1adf7ecf666fd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0c8489c8dd8846fba316b9d2490bdeee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u12.png"}},
{
              "id":"87df9517cca1428ba0c16a8dcb555596",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"89d1f00763554792a3401ae472ab022e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u29.png"}}]},
{
          "id":"f09d26aab32645cb92caa5dcc1a2140c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":105,
              "y":379},
            "size":{
              "width":101,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c2d8bbc7f2e4ba88cc5354706c2e776",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":105,
                  "y":379},
                "size":{
                  "width":101,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f5b521a4ef804c44ab073e6cd0afa669",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 链接",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/添加课程实验/u19.png"}},
{
          "id":"a2d6d424cf3142adae31165753838c44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":290},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b03182d5c1454336b6c8daef63726e98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":290},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e055e4ff19e94909a8f6c4243485c14a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":84},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e15fe318a2294df4a4950860605b7419",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":84},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee31dc68592c4883a93dd123571d07e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":120},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c11da9674af141dcb9d21c28f2f74d88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":120},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebd9b836165146aba5184c6a84ce778a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":250},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7203c53aab6b410ca68d2dbc29d3ce75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":250},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f2da8610c104abaada76686194b8f04",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":154},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5db74b9a28e14e64b7f450a6f284fb7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":154},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d57a4f80c37407c9e738a14f2ed020e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":84},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8296be4035394bec90eb1a96965ea17b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":84},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加课程实验/u32.png"}},
{
          "id":"3a03235365b74187a94ddbd91d238b51",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":120},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8ee9c38c46c4aa693c317850647a052",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":120},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加课程实验/u32.png"}},
{
          "id":"e6720ab44cbb4162b08e4683c0715189",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":154},
            "size":{
              "width":150,
              "height":69}},
          "adaptiveStyles":{
}},
{
          "id":"f996b80abd6e43ea8c86be2de110d33d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":247},
            "size":{
              "width":150,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"3f823ebf7c1e4c8abd5fc9a4aecb9b5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":340,
              "y":243},
            "size":{
              "width":190,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dcf8579f1c84cb9ba5a29c4a51e9be2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":340,
                  "y":243},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加课程实验/u38.png"}},
{
          "id":"73d9a9fa8ca94828a17d9789106cd5cb",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":455},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b0c430cee8fd47c0b3bcd7b6789b479b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":455},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"24bbd6a695f74db8861b45fc9e70f5c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":320,
              "y":470},
            "size":{
              "width":170,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c380c4976214e02838613a647c751f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":320,
                  "y":470},
                "size":{
                  "width":170,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加课程/u24.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "b7964d83ed7949d9acf07213a545fd69":{
      "scriptId":"u0"},
    "4c5f86c9db904b9fae92284aaeab1867":{
      "scriptId":"u1"},
    "7304dbcc4642457997a6e94589b9725a":{
      "scriptId":"u2"},
    "550827dd2a944a9f89d2caf8469ae6c1":{
      "scriptId":"u3"},
    "f11b3fee620e46058bbaf991719053a7":{
      "scriptId":"u4"},
    "1581ff3528394a3886aa7e57c936f075":{
      "scriptId":"u5"},
    "26da75ffdc124847b816a24d285a6b9d":{
      "scriptId":"u6"},
    "925d837a650142fc86aa9ea31ba20c80":{
      "scriptId":"u7"},
    "d811155171a0406089b6cbc82aaaff97":{
      "scriptId":"u8"},
    "9da0d011531b4539b8407e16c34e3ddf":{
      "scriptId":"u9"},
    "24701ee53b194ae2ba7fe81d5e00042b":{
      "scriptId":"u10"},
    "ff71d7baee4045ef8db1adf7ecf666fd":{
      "scriptId":"u11"},
    "0c8489c8dd8846fba316b9d2490bdeee":{
      "scriptId":"u12"},
    "d701dc9099a84a458bec3323c5b1d7bf":{
      "scriptId":"u13"},
    "5e4d7c9dfe71408eb85ce6c99143efbd":{
      "scriptId":"u14"},
    "3a1b4cc4339a4b2c86dd51b15e55b653":{
      "scriptId":"u15"},
    "d781a802f39849cc967b5a82e8992393":{
      "scriptId":"u16"},
    "87df9517cca1428ba0c16a8dcb555596":{
      "scriptId":"u17"},
    "89d1f00763554792a3401ae472ab022e":{
      "scriptId":"u18"},
    "f09d26aab32645cb92caa5dcc1a2140c":{
      "scriptId":"u19"},
    "4c2d8bbc7f2e4ba88cc5354706c2e776":{
      "scriptId":"u20"},
    "f5b521a4ef804c44ab073e6cd0afa669":{
      "scriptId":"u21"},
    "a2d6d424cf3142adae31165753838c44":{
      "scriptId":"u22"},
    "b03182d5c1454336b6c8daef63726e98":{
      "scriptId":"u23"},
    "e055e4ff19e94909a8f6c4243485c14a":{
      "scriptId":"u24"},
    "e15fe318a2294df4a4950860605b7419":{
      "scriptId":"u25"},
    "ee31dc68592c4883a93dd123571d07e1":{
      "scriptId":"u26"},
    "c11da9674af141dcb9d21c28f2f74d88":{
      "scriptId":"u27"},
    "ebd9b836165146aba5184c6a84ce778a":{
      "scriptId":"u28"},
    "7203c53aab6b410ca68d2dbc29d3ce75":{
      "scriptId":"u29"},
    "9f2da8610c104abaada76686194b8f04":{
      "scriptId":"u30"},
    "5db74b9a28e14e64b7f450a6f284fb7e":{
      "scriptId":"u31"},
    "8d57a4f80c37407c9e738a14f2ed020e":{
      "scriptId":"u32"},
    "8296be4035394bec90eb1a96965ea17b":{
      "scriptId":"u33"},
    "3a03235365b74187a94ddbd91d238b51":{
      "scriptId":"u34"},
    "d8ee9c38c46c4aa693c317850647a052":{
      "scriptId":"u35"},
    "e6720ab44cbb4162b08e4683c0715189":{
      "scriptId":"u36"},
    "f996b80abd6e43ea8c86be2de110d33d":{
      "scriptId":"u37"},
    "3f823ebf7c1e4c8abd5fc9a4aecb9b5e":{
      "scriptId":"u38"},
    "6dcf8579f1c84cb9ba5a29c4a51e9be2":{
      "scriptId":"u39"},
    "73d9a9fa8ca94828a17d9789106cd5cb":{
      "scriptId":"u40"},
    "b0c430cee8fd47c0b3bcd7b6789b479b":{
      "scriptId":"u41"},
    "24bbd6a695f74db8861b45fc9e70f5c9":{
      "scriptId":"u42"},
    "5c380c4976214e02838613a647c751f5":{
      "scriptId":"u43"}}});