$axure.loadCurrentPage({
  "url":"删除课程实验.html",
  "generationDate":new Date(1528362643532.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"08c29a30edd245d990d7592e5603b03c",
    "type":"Axure:Page",
    "name":"删除课程实验",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b04b1c89698a4e1e8ace04939ce79f0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":40,
              "y":70},
            "size":{
              "width":891,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f51088e057f34c39b96a46917b2ad9c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":40,
                  "y":70},
                "size":{
                  "width":891,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程实验/u45.png"}},
{
          "id":"aecb3fc62f264abcacd3176af59674c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":292,
              "y":77},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea60e72445d3427da5d162273df8216f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":292,
                  "y":77},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02d3cbfb451f4fedb38ab55ccb4499a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":350,
              "y":77},
            "size":{
              "width":91,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"403d5b036db44a4da195b51683016d27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":350,
                  "y":77},
                "size":{
                  "width":91,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程实验/u49.png"}},
{
          "id":"61dc354597b247b2a258ece9caf80c1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":77},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbba3dff5f3c40f4bfc927f893c7384e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":77},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bda16717f58743e1ac07482ab49b53db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":131,
              "y":77},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b17e887a90d440bba9a0ca418295b65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":131,
                  "y":77},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程实验/u53.png"}},
{
          "id":"2e9391012dc246da93b39a16ec1443c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":828,
              "y":77},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f09b549d88f46f790d72253960cff56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":828,
                  "y":77},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程实验/u55.png"}},
{
          "id":"f2441b8734324d188ec7059a5b1f0055",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":100},
            "size":{
              "width":891,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a29dc61e15a46739d62b0a0c92b671e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1dafdb3af13347309784fd358d2e20c4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u15.png"}},
{
              "id":"88b890b36cb54489a447403fdf3d04b6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6482230a03f64750a3133430348dfaaf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"95de2f1bd57b4ed183a197e4bb999ddd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ad0e60c31b254efa85291a277e2ae4fa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"ff6d3166245b41aea0054e49d20d8533",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5c0d5e04c06547ffb4d569dc9cc18612",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u15.png"}},
{
              "id":"c05c4ab802794ae2b6a375edf18f2fc1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c97759ccaa954459b293f00d0ae9c39e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"22014a93595e400ebee36fa4a5db0200",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"01350122f3db418fb78fe2ed193e09e9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"775a79c70a44470eb925e0c7cb0d8f13",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9571df59437c42279f88a325fc341dea",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u15.png"}},
{
              "id":"7693a97d524b467887a5b732326f248d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"79786b9bec4e4cc1bf6eb1ea6a05f905",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"781301ee625c48029675599a62534477",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"94f587be09df4974b925634fb00211b2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"bf45c38d971743509fa92d8756cb83b4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":119,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b0a6ed62ef4d4ab58b61cd5ece80c0da",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":119,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u74.png"}},
{
              "id":"ceb98eb7708a42b18375cdab2824ab7b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":36},
                "size":{
                  "width":119,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e920b63fbc8c48559aa0a654444fe1b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":36},
                    "size":{
                      "width":119,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u88.png"}},
{
              "id":"a34ce4de2c9744aab37cc69fe4bcf151",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":66},
                "size":{
                  "width":119,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0618496fac9e4aaf949935bca395c26f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":66},
                    "size":{
                      "width":119,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u103.png"}},
{
              "id":"53031de1fbc147caa42229b85bf21d9c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":555,
                  "y":0},
                "size":{
                  "width":117,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dfbc36f1e4984f2fb388100abc772d12",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":555,
                      "y":0},
                    "size":{
                      "width":117,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u78.png"}},
{
              "id":"74e3ed5c2adf4231adb32b9dd3ec11fa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":555,
                  "y":36},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1b01e553e88b4b21b13ab3e933f2110f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":555,
                      "y":36},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u92.png"}},
{
              "id":"211f2c88720844aaa99b64f9d1ef8e79",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":555,
                  "y":66},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"77a993a084984eea9ce1e637e7affb80",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":555,
                      "y":66},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u107.png"}},
{
              "id":"fb1769c537774cb6a5228debb3b6e42b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":419,
                  "y":0},
                "size":{
                  "width":136,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ab9c433e08ec4523939c8d25111d67d7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":419,
                      "y":0},
                    "size":{
                      "width":136,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u76.png"}},
{
              "id":"d8b7039feb8c4bc28714a511c24c86a3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":419,
                  "y":36},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5a8d16aa86d545eabcc5881491184c15",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":419,
                      "y":36},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u90.png"}},
{
              "id":"4d46e25dc0434a8a940ff1caecb71998",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":419,
                  "y":66},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9c5eb720d94b4b6fbb788b5821aea36e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":419,
                      "y":66},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u105.png"}},
{
              "id":"af68374a07664e60978b0c4805e16d64",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":672,
                  "y":0},
                "size":{
                  "width":108,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a7a1165ace6d4f2b98e6fad8a8a1f3c4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":672,
                      "y":0},
                    "size":{
                      "width":108,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑课程/u50.png"}},
{
              "id":"012659a1dbc64e378d12a89b29478e4d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":672,
                  "y":36},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"50087b6dbf6e496da2ac619c69cc4267",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":672,
                      "y":36},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"76cda912b7d5425aa400ea61282d9128",
                      "label":"",
                      "type":"hyperlink",
                      "styleType":"hyperlink",
                      "visible":true,
                      "style":{
},
                      "adaptiveStyles":{
},
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 编辑课程实验",
                                  "target":{
                                    "targetType":"page",
                                    "url":"编辑课程实验.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true}]}],
              "images":{
                "normal~":"images/编辑课程/u68.png"}},
{
              "id":"5b43bb82dded4949b799a4b9349ca8e2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":672,
                  "y":66},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9c9df81321734867a1e86486526bfbe6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":672,
                      "y":66},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5ffe8d5253de49d8995765f94a6ed3c3",
                      "label":"",
                      "type":"hyperlink",
                      "styleType":"hyperlink",
                      "visible":true,
                      "style":{
},
                      "adaptiveStyles":{
},
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 编辑课程实验",
                                  "target":{
                                    "targetType":"page",
                                    "url":"编辑课程实验.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true}]}],
              "images":{
                "normal~":"images/编辑课程/u88.png"}},
{
              "id":"2fe5372623e847d1b18dc6715287593a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":780,
                  "y":0},
                "size":{
                  "width":111,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a720d397cfbc42b4af57c9450e636db8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":780,
                      "y":0},
                    "size":{
                      "width":111,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑课程实验/u72.png"}},
{
              "id":"b752a7e502fa4916b30a6e42f865169d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":780,
                  "y":36},
                "size":{
                  "width":111,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d8306bb33ee549348e6b2c7514d43df5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":780,
                      "y":36},
                    "size":{
                      "width":111,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6cd98dfd4101496a90c6b2d618cc9a5a",
                      "label":"",
                      "type":"hyperlink",
                      "styleType":"hyperlink",
                      "visible":true,
                      "style":{
},
                      "adaptiveStyles":{
},
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 链接",
                                  "target":{
                                    "targetType":"page",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true}]}],
              "images":{
                "normal~":"images/编辑课程实验/u89.png"}},
{
              "id":"5af183c832ed463984273e3f0d6cf745",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":780,
                  "y":66},
                "size":{
                  "width":111,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9d34cb4ca6874597b2151f0306fdde2d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":780,
                      "y":66},
                    "size":{
                      "width":111,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ad73ef2978af4441903bc3b23d2d5eca",
                      "label":"",
                      "type":"hyperlink",
                      "styleType":"hyperlink",
                      "visible":true,
                      "style":{
},
                      "adaptiveStyles":{
},
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 链接",
                                  "target":{
                                    "targetType":"page",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true}]}],
              "images":{
                "normal~":"images/编辑课程实验/u107.png"}}]},
{
          "id":"8b3e5cc310d74ef5b8e6c8bf91c11a96",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":40,
              "y":196},
            "size":{
              "width":891,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f300aaec2784347b9e41ed730110259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":40,
                  "y":196},
                "size":{
                  "width":891,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程实验/u45.png"}},
{
          "id":"076de0b4113e4cf7b8f14dc06b93635e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":292,
              "y":203},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4b76db0198e4603b9745fe01db2fecf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":292,
                  "y":203},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf3231ae2b56436996bc442178caa8e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":350,
              "y":203},
            "size":{
              "width":91,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dabf6a302ad4102a831921b1ead295c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":350,
                  "y":203},
                "size":{
                  "width":91,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程实验/u49.png"}},
{
          "id":"e2960e2d9a0e49479c42e612203bd3cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":203},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb32d01789d84c418de859810ef4c36d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":203},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1dfda2f3b5e5429a95d415cff912c016",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":131,
              "y":203},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f744c65bb8be47f3838bb6e76dcc979f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":131,
                  "y":203},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程实验/u53.png"}},
{
          "id":"b44a8a85cc934edaa2ec39c85ca811d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":828,
              "y":203},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cffe10c235845f4a37c78ff0790564d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":828,
                  "y":203},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程实验/u55.png"}},
{
          "id":"8373c540946240a1ae5ef6d8fd8622d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":40,
              "y":226},
            "size":{
              "width":891,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f9ccf36df3f4f7fa8a5961f27596364",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":40,
                  "y":226},
                "size":{
                  "width":891,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程实验/u45.png"}},
{
          "id":"cc29f6d31ec54dfd9a298e589308a2de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":292,
              "y":233},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47f4ba91a28040e4b0b3e729cef0268c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":292,
                  "y":233},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7923e8af9b11460fab4834f6fa3ef957",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":350,
              "y":233},
            "size":{
              "width":91,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd859ebdb4d842128be9895ef0c9de9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":350,
                  "y":233},
                "size":{
                  "width":91,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程实验/u49.png"}},
{
          "id":"df3f08f58029445dbd35aa7d242f4bd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":233},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d4f33805383460fbaf6e71790868935",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":233},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa227c12f4cf48ec9c54bf8df5b12a7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":131,
              "y":233},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a29c14fab1f048bea5ad30a6d2ef7280",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":131,
                  "y":233},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程实验/u53.png"}},
{
          "id":"c341606b8f6043f7a09b9cc1aea97cf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":828,
              "y":233},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b9e73711f994fcbbe741c8ccc365c3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":828,
                  "y":233},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程实验/u55.png"}},
{
          "id":"40adecab9f354c6eb5a3b7276fd342cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":40,
              "y":256},
            "size":{
              "width":891,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f5bfe170f7b47d5895a923145b93aba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":40,
                  "y":256},
                "size":{
                  "width":891,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程实验/u45.png"}},
{
          "id":"a6ed7395ecab42d9b4776083445b6d6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":292,
              "y":263},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb8a808fbaaf48828dbe4da785918143",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":292,
                  "y":263},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"114556d5c29545929fd780672d64a933",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":350,
              "y":263},
            "size":{
              "width":91,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd951903a8c64dc98743d39315eccae8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":350,
                  "y":263},
                "size":{
                  "width":91,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程实验/u49.png"}},
{
          "id":"1f9156961f2b40baaf21f89227ec32a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":263},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1702e6e1277942599361b89bc9f1b73f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":263},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32b9530f1c1a44c690397bed9203ee6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":131,
              "y":263},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f74161436ca14627a53b07bc9a4a7dac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":131,
                  "y":263},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程实验/u53.png"}},
{
          "id":"40d7bde407ca4f6e948c80d5fa2c2787",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":828,
              "y":263},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"392d2d974d144c9688f6ea17ec643bc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":828,
                  "y":263},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程实验/u55.png"}},
{
          "id":"b32a6719446f4bf1a27b425b1d81a410",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":40,
              "y":296},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cf4eba2bcfa4453ab606df86263ecaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":40,
                  "y":296},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u112.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "b04b1c89698a4e1e8ace04939ce79f0f":{
      "scriptId":"u0"},
    "f51088e057f34c39b96a46917b2ad9c1":{
      "scriptId":"u1"},
    "aecb3fc62f264abcacd3176af59674c4":{
      "scriptId":"u2"},
    "ea60e72445d3427da5d162273df8216f":{
      "scriptId":"u3"},
    "02d3cbfb451f4fedb38ab55ccb4499a4":{
      "scriptId":"u4"},
    "403d5b036db44a4da195b51683016d27":{
      "scriptId":"u5"},
    "61dc354597b247b2a258ece9caf80c1c":{
      "scriptId":"u6"},
    "fbba3dff5f3c40f4bfc927f893c7384e":{
      "scriptId":"u7"},
    "bda16717f58743e1ac07482ab49b53db":{
      "scriptId":"u8"},
    "5b17e887a90d440bba9a0ca418295b65":{
      "scriptId":"u9"},
    "2e9391012dc246da93b39a16ec1443c9":{
      "scriptId":"u10"},
    "3f09b549d88f46f790d72253960cff56":{
      "scriptId":"u11"},
    "f2441b8734324d188ec7059a5b1f0055":{
      "scriptId":"u12"},
    "8a29dc61e15a46739d62b0a0c92b671e":{
      "scriptId":"u13"},
    "1dafdb3af13347309784fd358d2e20c4":{
      "scriptId":"u14"},
    "ff6d3166245b41aea0054e49d20d8533":{
      "scriptId":"u15"},
    "5c0d5e04c06547ffb4d569dc9cc18612":{
      "scriptId":"u16"},
    "775a79c70a44470eb925e0c7cb0d8f13":{
      "scriptId":"u17"},
    "9571df59437c42279f88a325fc341dea":{
      "scriptId":"u18"},
    "bf45c38d971743509fa92d8756cb83b4":{
      "scriptId":"u19"},
    "b0a6ed62ef4d4ab58b61cd5ece80c0da":{
      "scriptId":"u20"},
    "fb1769c537774cb6a5228debb3b6e42b":{
      "scriptId":"u21"},
    "ab9c433e08ec4523939c8d25111d67d7":{
      "scriptId":"u22"},
    "53031de1fbc147caa42229b85bf21d9c":{
      "scriptId":"u23"},
    "dfbc36f1e4984f2fb388100abc772d12":{
      "scriptId":"u24"},
    "af68374a07664e60978b0c4805e16d64":{
      "scriptId":"u25"},
    "a7a1165ace6d4f2b98e6fad8a8a1f3c4":{
      "scriptId":"u26"},
    "2fe5372623e847d1b18dc6715287593a":{
      "scriptId":"u27"},
    "a720d397cfbc42b4af57c9450e636db8":{
      "scriptId":"u28"},
    "88b890b36cb54489a447403fdf3d04b6":{
      "scriptId":"u29"},
    "6482230a03f64750a3133430348dfaaf":{
      "scriptId":"u30"},
    "c05c4ab802794ae2b6a375edf18f2fc1":{
      "scriptId":"u31"},
    "c97759ccaa954459b293f00d0ae9c39e":{
      "scriptId":"u32"},
    "7693a97d524b467887a5b732326f248d":{
      "scriptId":"u33"},
    "79786b9bec4e4cc1bf6eb1ea6a05f905":{
      "scriptId":"u34"},
    "ceb98eb7708a42b18375cdab2824ab7b":{
      "scriptId":"u35"},
    "e920b63fbc8c48559aa0a654444fe1b9":{
      "scriptId":"u36"},
    "d8b7039feb8c4bc28714a511c24c86a3":{
      "scriptId":"u37"},
    "5a8d16aa86d545eabcc5881491184c15":{
      "scriptId":"u38"},
    "74e3ed5c2adf4231adb32b9dd3ec11fa":{
      "scriptId":"u39"},
    "1b01e553e88b4b21b13ab3e933f2110f":{
      "scriptId":"u40"},
    "012659a1dbc64e378d12a89b29478e4d":{
      "scriptId":"u41"},
    "50087b6dbf6e496da2ac619c69cc4267":{
      "scriptId":"u42"},
    "76cda912b7d5425aa400ea61282d9128":{
      "scriptId":"u43"},
    "b752a7e502fa4916b30a6e42f865169d":{
      "scriptId":"u44"},
    "d8306bb33ee549348e6b2c7514d43df5":{
      "scriptId":"u45"},
    "6cd98dfd4101496a90c6b2d618cc9a5a":{
      "scriptId":"u46"},
    "95de2f1bd57b4ed183a197e4bb999ddd":{
      "scriptId":"u47"},
    "ad0e60c31b254efa85291a277e2ae4fa":{
      "scriptId":"u48"},
    "22014a93595e400ebee36fa4a5db0200":{
      "scriptId":"u49"},
    "01350122f3db418fb78fe2ed193e09e9":{
      "scriptId":"u50"},
    "781301ee625c48029675599a62534477":{
      "scriptId":"u51"},
    "94f587be09df4974b925634fb00211b2":{
      "scriptId":"u52"},
    "a34ce4de2c9744aab37cc69fe4bcf151":{
      "scriptId":"u53"},
    "0618496fac9e4aaf949935bca395c26f":{
      "scriptId":"u54"},
    "4d46e25dc0434a8a940ff1caecb71998":{
      "scriptId":"u55"},
    "9c5eb720d94b4b6fbb788b5821aea36e":{
      "scriptId":"u56"},
    "211f2c88720844aaa99b64f9d1ef8e79":{
      "scriptId":"u57"},
    "77a993a084984eea9ce1e637e7affb80":{
      "scriptId":"u58"},
    "5b43bb82dded4949b799a4b9349ca8e2":{
      "scriptId":"u59"},
    "9c9df81321734867a1e86486526bfbe6":{
      "scriptId":"u60"},
    "5ffe8d5253de49d8995765f94a6ed3c3":{
      "scriptId":"u61"},
    "5af183c832ed463984273e3f0d6cf745":{
      "scriptId":"u62"},
    "9d34cb4ca6874597b2151f0306fdde2d":{
      "scriptId":"u63"},
    "ad73ef2978af4441903bc3b23d2d5eca":{
      "scriptId":"u64"},
    "8b3e5cc310d74ef5b8e6c8bf91c11a96":{
      "scriptId":"u65"},
    "8f300aaec2784347b9e41ed730110259":{
      "scriptId":"u66"},
    "076de0b4113e4cf7b8f14dc06b93635e":{
      "scriptId":"u67"},
    "f4b76db0198e4603b9745fe01db2fecf":{
      "scriptId":"u68"},
    "cf3231ae2b56436996bc442178caa8e2":{
      "scriptId":"u69"},
    "0dabf6a302ad4102a831921b1ead295c":{
      "scriptId":"u70"},
    "e2960e2d9a0e49479c42e612203bd3cb":{
      "scriptId":"u71"},
    "fb32d01789d84c418de859810ef4c36d":{
      "scriptId":"u72"},
    "1dfda2f3b5e5429a95d415cff912c016":{
      "scriptId":"u73"},
    "f744c65bb8be47f3838bb6e76dcc979f":{
      "scriptId":"u74"},
    "b44a8a85cc934edaa2ec39c85ca811d8":{
      "scriptId":"u75"},
    "8cffe10c235845f4a37c78ff0790564d":{
      "scriptId":"u76"},
    "8373c540946240a1ae5ef6d8fd8622d5":{
      "scriptId":"u77"},
    "4f9ccf36df3f4f7fa8a5961f27596364":{
      "scriptId":"u78"},
    "cc29f6d31ec54dfd9a298e589308a2de":{
      "scriptId":"u79"},
    "47f4ba91a28040e4b0b3e729cef0268c":{
      "scriptId":"u80"},
    "7923e8af9b11460fab4834f6fa3ef957":{
      "scriptId":"u81"},
    "dd859ebdb4d842128be9895ef0c9de9e":{
      "scriptId":"u82"},
    "df3f08f58029445dbd35aa7d242f4bd1":{
      "scriptId":"u83"},
    "8d4f33805383460fbaf6e71790868935":{
      "scriptId":"u84"},
    "aa227c12f4cf48ec9c54bf8df5b12a7b":{
      "scriptId":"u85"},
    "a29c14fab1f048bea5ad30a6d2ef7280":{
      "scriptId":"u86"},
    "c341606b8f6043f7a09b9cc1aea97cf4":{
      "scriptId":"u87"},
    "2b9e73711f994fcbbe741c8ccc365c3a":{
      "scriptId":"u88"},
    "40adecab9f354c6eb5a3b7276fd342cc":{
      "scriptId":"u89"},
    "7f5bfe170f7b47d5895a923145b93aba":{
      "scriptId":"u90"},
    "a6ed7395ecab42d9b4776083445b6d6d":{
      "scriptId":"u91"},
    "eb8a808fbaaf48828dbe4da785918143":{
      "scriptId":"u92"},
    "114556d5c29545929fd780672d64a933":{
      "scriptId":"u93"},
    "dd951903a8c64dc98743d39315eccae8":{
      "scriptId":"u94"},
    "1f9156961f2b40baaf21f89227ec32a2":{
      "scriptId":"u95"},
    "1702e6e1277942599361b89bc9f1b73f":{
      "scriptId":"u96"},
    "32b9530f1c1a44c690397bed9203ee6f":{
      "scriptId":"u97"},
    "f74161436ca14627a53b07bc9a4a7dac":{
      "scriptId":"u98"},
    "40d7bde407ca4f6e948c80d5fa2c2787":{
      "scriptId":"u99"},
    "392d2d974d144c9688f6ea17ec643bc9":{
      "scriptId":"u100"},
    "b32a6719446f4bf1a27b425b1d81a410":{
      "scriptId":"u101"},
    "0cf4eba2bcfa4453ab606df86263ecaa":{
      "scriptId":"u102"}}});