$axure.loadCurrentPage({
  "url":"登出.html",
  "generationDate":new Date(1528362643868.03),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e063108a66a84b0dbb7e9d39b92f8c7f",
    "type":"Axure:Page",
    "name":"登出",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"11effbeaa15f4869a106aec19158d0b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":30,
              "y":60},
            "size":{
              "width":840,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a459d7b4c07148adb139b7a352742697",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":30,
                  "y":60},
                "size":{
                  "width":840,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"35e1414f86184281bba441f95a4bf4f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":40,
              "y":69},
            "size":{
              "width":205,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6765b0a50c794694880fc44c9d4e3730",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":40,
                  "y":69},
                "size":{
                  "width":205,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"e880e4742d9649bdb22f4b4fa31830e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":283,
              "y":69},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7847bb2c54704ef5a2769e2d86e49290",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":283,
                  "y":69},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7603b65e9c294aa8b0fe8d7912c49be8",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"700"},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"21393aa310fc4df7923e8409eb5e09c1",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":69},
            "size":{
              "width":210,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"20ab833b189f45a7b38ad82c8dc2d5c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":660,
              "y":69},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc35c29daa2d4d31b8d2f255735d9c2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":660,
                  "y":69},
                "size":{
                  "width":100,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"13940db6b9354bb3bf1d008d3f8fa3a2",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":759,
              "y":69},
            "size":{
              "width":9,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98e9ef0ed0e74fb98f48b7df4bafbd95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":759,
                  "y":69},
                "size":{
                  "width":9,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u10.png"}},
{
          "id":"afdd301ab28344bd997db2350dba1366",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":756,
              "y":69},
            "size":{
              "width":15,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e92b4c3f0d549b1afd2cad4acc3e93f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":756,
                  "y":69},
                "size":{
                  "width":15,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u12.png"}},
{
          "id":"3b09bb7226284865b168e702d69316fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":30,
              "y":150},
            "size":{
              "width":840,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0726bf951e843ecbb34b04ca55681af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":30,
                  "y":150},
                "size":{
                  "width":840,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"7059b25c0cd041e3aad68ca525e1940b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":40,
              "y":159},
            "size":{
              "width":205,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f8b260d3a4f4abba520d810a7252c5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":40,
                  "y":159},
                "size":{
                  "width":205,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"427e3f40d8474338828de8cc4cd6b13b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":283,
              "y":159},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04eef4ddc0c346e1829ef8a6910821f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":283,
                  "y":159},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eef3419bebfa47dab45be4e27611cef8",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"700"},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"4d12f559a9df4f07809c9df13d4d89b3",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":159},
            "size":{
              "width":210,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"f56c602d40824370a6bd5f5cf7f46ef3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":660,
              "y":159},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c36f38970ceb4f008b423d8e846ed254",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":660,
                  "y":159},
                "size":{
                  "width":100,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u24.png"}},
{
          "id":"d41024eab7e34258a0c4e46c1fd60c31",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":764,
              "y":160},
            "size":{
              "width":9,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7634129015346ca86ce03093b44803e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":764,
                  "y":160},
                "size":{
                  "width":9,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u10.png"}},
{
          "id":"f61823d776aa4fc597bf562e30b4fcbe",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":761,
              "y":160},
            "size":{
              "width":15,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97ea3921c2c44c338a92f38a2913f057",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":761,
                  "y":160},
                "size":{
                  "width":15,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u12.png"}},
{
          "id":"66d2589c92e346d5957faad398e05798",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":660,
              "y":180},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac0a08080b1249bdabad1ab33318758d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":660,
                  "y":180},
                "size":{
                  "width":100,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0c009ef43905459a825f9ce6f88665e4",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 查看用户信息",
                              "target":{
                                "targetType":"page",
                                "url":"查看用户信息.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/首页/u24.png"}},
{
          "id":"0be58c9e22c24f5fabcd7d3436d50566",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":660,
              "y":201},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"493c2da4988b485594166bd63220c994",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":660,
                  "y":201},
                "size":{
                  "width":100,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9c56fc839c304a249dfa419c14cc8b5f",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 修改用户信息",
                              "target":{
                                "targetType":"page",
                                "url":"修改用户信息.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/首页/u24.png"}},
{
          "id":"ee74394ef5334125bfde32c90c808a84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":660,
              "y":222},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6ed3a514a244292a119b94d2b39d3af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":660,
                  "y":222},
                "size":{
                  "width":100,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"57f1c1c24e784d1d95ffd5f16594b984",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 修改密码",
                              "target":{
                                "targetType":"page",
                                "url":"修改密码.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/首页/u24.png"}},
{
          "id":"279c74003fa54bacb14314b4d0c9fff5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":660,
              "y":243},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"254f209b1d7d47b48b5420cc2686e05e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":660,
                  "y":243},
                "size":{
                  "width":100,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ca28c197afe3449cbfcae4158f693d51",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 登出",
                              "target":{
                                "targetType":"page",
                                "url":"登出.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/首页/u24.png"}},
{
          "id":"adf2bdf88a504c9a8ba0a1b41427077c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":30,
              "y":300},
            "size":{
              "width":840,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db08aa4d9b044b2bba5553d474f1e2ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":30,
                  "y":300},
                "size":{
                  "width":840,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"8481088b5dd840269394ab6f83b49593",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":40,
              "y":309},
            "size":{
              "width":205,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"272f8b64bc324b3e96c9d99c81f1ef0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":40,
                  "y":309},
                "size":{
                  "width":205,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"bf84f9b3d7af4ab1921fa3f4fc45df90",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":283,
              "y":309},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2c9d027711a45ffa26a11c9509a2910",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":283,
                  "y":309},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"03715e2d87294fb4a12f330a920e2bb8",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"700"},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"5046a926e98a46c5a8246996445c1c15",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":309},
            "size":{
              "width":210,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"fc345f784fde4f17af73b017914a280a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":660,
              "y":309},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cb5696469c9447dbd16921a712a84c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":660,
                  "y":309},
                "size":{
                  "width":100,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a3d5baf369ca4438a6e375774ede8e0d",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 登录",
                              "target":{
                                "targetType":"page",
                                "url":"登录.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"795eaeeae51749fb8d90c1c194c5f2d1",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":759,
              "y":309},
            "size":{
              "width":9,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca5e7d5f78c3415e810d46ff7491321b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":759,
                  "y":309},
                "size":{
                  "width":9,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u10.png"}},
{
          "id":"de3d4e4031704741914eb91f56b834ae",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":756,
              "y":309},
            "size":{
              "width":15,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b24052a37864464ac34b904f757a214",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":756,
                  "y":309},
                "size":{
                  "width":15,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u12.png"}},
{
          "id":"cb774495f32b4c28a61f84fee980cebd",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":150},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bddf816435a4149b519416c3dd0c14b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":890,
                  "y":150},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}},
{
          "id":"446bec5242384ec0bb4a4359f1bd4505",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":300},
            "size":{
              "width":110,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aef1f991225f4462b79a4cff1fe276f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":890,
                  "y":300},
                "size":{
                  "width":110,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u59.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "11effbeaa15f4869a106aec19158d0b3":{
      "scriptId":"u0"},
    "a459d7b4c07148adb139b7a352742697":{
      "scriptId":"u1"},
    "35e1414f86184281bba441f95a4bf4f0":{
      "scriptId":"u2"},
    "6765b0a50c794694880fc44c9d4e3730":{
      "scriptId":"u3"},
    "e880e4742d9649bdb22f4b4fa31830e4":{
      "scriptId":"u4"},
    "7847bb2c54704ef5a2769e2d86e49290":{
      "scriptId":"u5"},
    "7603b65e9c294aa8b0fe8d7912c49be8":{
      "scriptId":"u6"},
    "21393aa310fc4df7923e8409eb5e09c1":{
      "scriptId":"u7"},
    "20ab833b189f45a7b38ad82c8dc2d5c1":{
      "scriptId":"u8"},
    "dc35c29daa2d4d31b8d2f255735d9c2a":{
      "scriptId":"u9"},
    "13940db6b9354bb3bf1d008d3f8fa3a2":{
      "scriptId":"u10"},
    "98e9ef0ed0e74fb98f48b7df4bafbd95":{
      "scriptId":"u11"},
    "afdd301ab28344bd997db2350dba1366":{
      "scriptId":"u12"},
    "9e92b4c3f0d549b1afd2cad4acc3e93f":{
      "scriptId":"u13"},
    "3b09bb7226284865b168e702d69316fc":{
      "scriptId":"u14"},
    "e0726bf951e843ecbb34b04ca55681af":{
      "scriptId":"u15"},
    "7059b25c0cd041e3aad68ca525e1940b":{
      "scriptId":"u16"},
    "2f8b260d3a4f4abba520d810a7252c5e":{
      "scriptId":"u17"},
    "427e3f40d8474338828de8cc4cd6b13b":{
      "scriptId":"u18"},
    "04eef4ddc0c346e1829ef8a6910821f8":{
      "scriptId":"u19"},
    "eef3419bebfa47dab45be4e27611cef8":{
      "scriptId":"u20"},
    "4d12f559a9df4f07809c9df13d4d89b3":{
      "scriptId":"u21"},
    "f56c602d40824370a6bd5f5cf7f46ef3":{
      "scriptId":"u22"},
    "c36f38970ceb4f008b423d8e846ed254":{
      "scriptId":"u23"},
    "d41024eab7e34258a0c4e46c1fd60c31":{
      "scriptId":"u24"},
    "b7634129015346ca86ce03093b44803e":{
      "scriptId":"u25"},
    "f61823d776aa4fc597bf562e30b4fcbe":{
      "scriptId":"u26"},
    "97ea3921c2c44c338a92f38a2913f057":{
      "scriptId":"u27"},
    "66d2589c92e346d5957faad398e05798":{
      "scriptId":"u28"},
    "ac0a08080b1249bdabad1ab33318758d":{
      "scriptId":"u29"},
    "0c009ef43905459a825f9ce6f88665e4":{
      "scriptId":"u30"},
    "0be58c9e22c24f5fabcd7d3436d50566":{
      "scriptId":"u31"},
    "493c2da4988b485594166bd63220c994":{
      "scriptId":"u32"},
    "9c56fc839c304a249dfa419c14cc8b5f":{
      "scriptId":"u33"},
    "ee74394ef5334125bfde32c90c808a84":{
      "scriptId":"u34"},
    "f6ed3a514a244292a119b94d2b39d3af":{
      "scriptId":"u35"},
    "57f1c1c24e784d1d95ffd5f16594b984":{
      "scriptId":"u36"},
    "279c74003fa54bacb14314b4d0c9fff5":{
      "scriptId":"u37"},
    "254f209b1d7d47b48b5420cc2686e05e":{
      "scriptId":"u38"},
    "ca28c197afe3449cbfcae4158f693d51":{
      "scriptId":"u39"},
    "adf2bdf88a504c9a8ba0a1b41427077c":{
      "scriptId":"u40"},
    "db08aa4d9b044b2bba5553d474f1e2ed":{
      "scriptId":"u41"},
    "8481088b5dd840269394ab6f83b49593":{
      "scriptId":"u42"},
    "272f8b64bc324b3e96c9d99c81f1ef0d":{
      "scriptId":"u43"},
    "bf84f9b3d7af4ab1921fa3f4fc45df90":{
      "scriptId":"u44"},
    "c2c9d027711a45ffa26a11c9509a2910":{
      "scriptId":"u45"},
    "03715e2d87294fb4a12f330a920e2bb8":{
      "scriptId":"u46"},
    "5046a926e98a46c5a8246996445c1c15":{
      "scriptId":"u47"},
    "fc345f784fde4f17af73b017914a280a":{
      "scriptId":"u48"},
    "4cb5696469c9447dbd16921a712a84c5":{
      "scriptId":"u49"},
    "a3d5baf369ca4438a6e375774ede8e0d":{
      "scriptId":"u50"},
    "795eaeeae51749fb8d90c1c194c5f2d1":{
      "scriptId":"u51"},
    "ca5e7d5f78c3415e810d46ff7491321b":{
      "scriptId":"u52"},
    "de3d4e4031704741914eb91f56b834ae":{
      "scriptId":"u53"},
    "6b24052a37864464ac34b904f757a214":{
      "scriptId":"u54"},
    "cb774495f32b4c28a61f84fee980cebd":{
      "scriptId":"u55"},
    "8bddf816435a4149b519416c3dd0c14b":{
      "scriptId":"u56"},
    "446bec5242384ec0bb4a4359f1bd4505":{
      "scriptId":"u57"},
    "aef1f991225f4462b79a4cff1fe276f7":{
      "scriptId":"u58"}}});