$axure.loadCurrentPage({
  "url":"课程列表.html",
  "generationDate":new Date(1528362641950),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c9cb52dd30a64548b4629ce7dac17ec6",
    "type":"Axure:Page",
    "name":"课程列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"23ce7325af0e4e82a56e66cdbba63144",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":50},
            "size":{
              "width":500,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37cf4605f9004d03afa7723e1186a62b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":122,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0396bb8d1fb048259330bfcb065a5f60",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":122,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u1.png"}},
{
              "id":"6c829722fafe4e7b85cb9514c8767749",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":122,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e2b8a3744d324938982ac45a6b451e1c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":122,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u11.png"}},
{
              "id":"35e3bc22b6c741ffa8376e52a6e40914",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":122,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9b36ab0011024171959e82813920c8e0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":122,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u22.png"}},
{
              "id":"2e5541f498a44b8ca868329fbbed35d2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":122,
                  "y":0},
                "size":{
                  "width":78,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"02debaaa458a42e3a767cfd4d2effdb9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":122,
                      "y":0},
                    "size":{
                      "width":78,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u3.png"}},
{
              "id":"c86153b563da4900a35070729f156ad6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":122,
                  "y":30},
                "size":{
                  "width":78,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"27a74e7ff9d34e04a0da43d00622c1d1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":122,
                      "y":30},
                    "size":{
                      "width":78,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u13.png"}},
{
              "id":"36aec0e434644a33951a883b1a65097c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":122,
                  "y":66},
                "size":{
                  "width":78,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4958d6b429c742be8d8a97dad42e7428",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":122,
                      "y":66},
                    "size":{
                      "width":78,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u24.png"}},
{
              "id":"a83b752ab6154450bcaddc568759b6d7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6767bff7c5a141338aedf43df36b1c84",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"23d4521a307d4adf9fc04555c30aa859",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f93d8b14d3e94cc29179c976797ee460",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u15.png"}},
{
              "id":"cc40a526242b4c77bcb4715377ca7e94",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"79b10286f3f64a63b2244086f16afd0d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"cd56f5bfc5a24c93b74cfeafd3a0dd54",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1ec0ef8ad4d8433386e741c956971fc3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"4da9c9d40433436eb930d040ae31eb5b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":30},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f6ae952a94414df68e5c23b40102db5b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u15.png"}},
{
              "id":"f26e8587bd3e4743b275a1639f1366da",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"96d670f0f5504f798cc944910d1ccecf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"2b9adcafe1ed40ffbb4d5105471d6226",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c603e2538fe749979f546cb4d39e6ad9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u12.png"}},
{
              "id":"2edec8dcd7ce4134b2cde629782b540e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":400,
                  "y":30},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"70ba09079a63441fbb8c9a15fba4aa09",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":400,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9d7ec4ba54f3442f94a2e4bb1e4b0844",
                      "label":"",
                      "type":"hyperlink",
                      "styleType":"hyperlink",
                      "visible":true,
                      "style":{
},
                      "adaptiveStyles":{
},
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 链接",
                                  "target":{
                                    "targetType":"page",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true}]}],
              "images":{
                "normal~":"images/课程列表/u19.png"}},
{
              "id":"158b89bd2b254dc3a317af7119b17a3d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":400,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a30862bce31d493b9a5ea526f336c854",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":400,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5086e1494187462f9d0c4866fe856e99",
                      "label":"",
                      "type":"hyperlink",
                      "styleType":"hyperlink",
                      "visible":true,
                      "style":{
},
                      "adaptiveStyles":{
},
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 链接",
                                  "target":{
                                    "targetType":"page",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true}]}],
              "images":{
                "normal~":"images/选课/u29.png"}}]},
{
          "id":"0dff1d2eb91b44e887c40a9e3759b3e8",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":270},
            "size":{
              "width":700,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93eae8a2680b46a3817f239e5bef12ff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8574c2984b84465d827c1614c4a7ccb7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"5ab754a611604a98946427eaedce5170",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ce67ea38758b45888054e92b3f3607f1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u15.png"}},
{
              "id":"25639464e7e249b29293ca977df36db2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c7dd3dfb851249bcb2da28560650e216",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"36b2c41c56c04902a8d1460ba9872a53",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a2946b2b9818467995a7b4d9c796de36",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"66b3c650c0cc4da382d7205218e4b1c3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e60e5e86d64f49259116b492f52bc015",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u15.png"}},
{
              "id":"7462b2d03e6f4ce5a9a1918fc1c145df",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e9fd8cf999654a15b21ddbe5578c0f14",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"3a5f17fc4ec741b0bb2f0f7f20ee5e37",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3510d8077e1f41f7a7fb910c4b337132",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"26dd3a6a6f3440cdbb18496efd6a09b9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":30},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"631e252d9db5491fa15bc060bf36dca5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u15.png"}},
{
              "id":"c4b2606e8dcc40bd825edfc6a684142b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7d7e3c9a7ba44b78b7677e14e635a21a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"cff0b7905c114a7b80d33d371c578925",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"73bf79606c0444df85a1f64f68509949",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"f98b1f7bf1fe454d92b0b5ef53576070",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f1687d6497734187a5d01fdb84215d4e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u15.png"}},
{
              "id":"ca2733f429824aa384badf36a26d1411",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e831dc0559844057b1e969031171b422",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"6736b7183bb347caa193cce0ff6679c0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dcdece19de6742a7b032aff8384bcafb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"ac877cef1033465e8f96adf8862b5369",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":30},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"af9b39e142df4897b3b37d23aac44112",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u15.png"}},
{
              "id":"8fdc00e30c5f4297a09c6a825fffc315",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"316cb704caa74cd6aa4ba4103dd06b21",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"d20280470c7042cc904c43ae27f28723",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":143,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eaf04f00774b4ed289b867b35b080d3c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":143,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u44.png"}},
{
              "id":"ad451ba2a565445ca794b8e475553d22",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":30},
                "size":{
                  "width":143,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"19c40a12917b4d328a39132da82bab96",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":30},
                    "size":{
                      "width":143,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u58.png"}},
{
              "id":"798f4d432c7c46a3959f1d84335ec4fe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":66},
                "size":{
                  "width":143,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"01dbed9ebc5b47f6875ad6b352baf239",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":66},
                    "size":{
                      "width":143,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u73.png"}},
{
              "id":"3b6b9403932744da9cd15770cb8da4e1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":643,
                  "y":0},
                "size":{
                  "width":57,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9ed6504f1bb24c3895a570588d0db943",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":643,
                      "y":0},
                    "size":{
                      "width":57,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u46.png"}},
{
              "id":"8fb9dff57bc0419bacca932942cdc51f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":643,
                  "y":30},
                "size":{
                  "width":57,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"24929ac59c5c44bfb368065e393e2f00",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":643,
                      "y":30},
                    "size":{
                      "width":57,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1d9a0cc986f949d5ae9200700c02e76a",
                      "label":"",
                      "type":"hyperlink",
                      "styleType":"hyperlink",
                      "visible":true,
                      "style":{
},
                      "adaptiveStyles":{
},
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 链接",
                                  "target":{
                                    "targetType":"page",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true}]}],
              "images":{
                "normal~":"images/课程列表/u60.png"}},
{
              "id":"588e6967cac4434fa1a16f8161a0c76b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":643,
                  "y":66},
                "size":{
                  "width":57,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a310e9d442644939b012bf8094267a9b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":643,
                      "y":66},
                    "size":{
                      "width":57,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8f2c2c72786f4de6ab9e6308d4eceea2",
                      "label":"",
                      "type":"hyperlink",
                      "styleType":"hyperlink",
                      "visible":true,
                      "style":{
},
                      "adaptiveStyles":{
},
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 链接",
                                  "target":{
                                    "targetType":"page",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true}]}],
              "images":{
                "normal~":"images/课程列表/u75.png"}}]},
{
          "id":"d7d8537532fa44cc9a67d6c72d3b6d3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":640,
              "y":130},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01a62b5e232f48cbab3a4c4dc00d2a02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":640,
                  "y":130},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u22.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "23ce7325af0e4e82a56e66cdbba63144":{
      "scriptId":"u0"},
    "37cf4605f9004d03afa7723e1186a62b":{
      "scriptId":"u1"},
    "0396bb8d1fb048259330bfcb065a5f60":{
      "scriptId":"u2"},
    "2e5541f498a44b8ca868329fbbed35d2":{
      "scriptId":"u3"},
    "02debaaa458a42e3a767cfd4d2effdb9":{
      "scriptId":"u4"},
    "a83b752ab6154450bcaddc568759b6d7":{
      "scriptId":"u5"},
    "6767bff7c5a141338aedf43df36b1c84":{
      "scriptId":"u6"},
    "cd56f5bfc5a24c93b74cfeafd3a0dd54":{
      "scriptId":"u7"},
    "1ec0ef8ad4d8433386e741c956971fc3":{
      "scriptId":"u8"},
    "2b9adcafe1ed40ffbb4d5105471d6226":{
      "scriptId":"u9"},
    "c603e2538fe749979f546cb4d39e6ad9":{
      "scriptId":"u10"},
    "6c829722fafe4e7b85cb9514c8767749":{
      "scriptId":"u11"},
    "e2b8a3744d324938982ac45a6b451e1c":{
      "scriptId":"u12"},
    "c86153b563da4900a35070729f156ad6":{
      "scriptId":"u13"},
    "27a74e7ff9d34e04a0da43d00622c1d1":{
      "scriptId":"u14"},
    "23d4521a307d4adf9fc04555c30aa859":{
      "scriptId":"u15"},
    "f93d8b14d3e94cc29179c976797ee460":{
      "scriptId":"u16"},
    "4da9c9d40433436eb930d040ae31eb5b":{
      "scriptId":"u17"},
    "f6ae952a94414df68e5c23b40102db5b":{
      "scriptId":"u18"},
    "2edec8dcd7ce4134b2cde629782b540e":{
      "scriptId":"u19"},
    "70ba09079a63441fbb8c9a15fba4aa09":{
      "scriptId":"u20"},
    "9d7ec4ba54f3442f94a2e4bb1e4b0844":{
      "scriptId":"u21"},
    "35e3bc22b6c741ffa8376e52a6e40914":{
      "scriptId":"u22"},
    "9b36ab0011024171959e82813920c8e0":{
      "scriptId":"u23"},
    "36aec0e434644a33951a883b1a65097c":{
      "scriptId":"u24"},
    "4958d6b429c742be8d8a97dad42e7428":{
      "scriptId":"u25"},
    "cc40a526242b4c77bcb4715377ca7e94":{
      "scriptId":"u26"},
    "79b10286f3f64a63b2244086f16afd0d":{
      "scriptId":"u27"},
    "f26e8587bd3e4743b275a1639f1366da":{
      "scriptId":"u28"},
    "96d670f0f5504f798cc944910d1ccecf":{
      "scriptId":"u29"},
    "158b89bd2b254dc3a317af7119b17a3d":{
      "scriptId":"u30"},
    "a30862bce31d493b9a5ea526f336c854":{
      "scriptId":"u31"},
    "5086e1494187462f9d0c4866fe856e99":{
      "scriptId":"u32"},
    "0dff1d2eb91b44e887c40a9e3759b3e8":{
      "scriptId":"u33"},
    "cff0b7905c114a7b80d33d371c578925":{
      "scriptId":"u34"},
    "73bf79606c0444df85a1f64f68509949":{
      "scriptId":"u35"},
    "93eae8a2680b46a3817f239e5bef12ff":{
      "scriptId":"u36"},
    "8574c2984b84465d827c1614c4a7ccb7":{
      "scriptId":"u37"},
    "36b2c41c56c04902a8d1460ba9872a53":{
      "scriptId":"u38"},
    "a2946b2b9818467995a7b4d9c796de36":{
      "scriptId":"u39"},
    "3a5f17fc4ec741b0bb2f0f7f20ee5e37":{
      "scriptId":"u40"},
    "3510d8077e1f41f7a7fb910c4b337132":{
      "scriptId":"u41"},
    "6736b7183bb347caa193cce0ff6679c0":{
      "scriptId":"u42"},
    "dcdece19de6742a7b032aff8384bcafb":{
      "scriptId":"u43"},
    "d20280470c7042cc904c43ae27f28723":{
      "scriptId":"u44"},
    "eaf04f00774b4ed289b867b35b080d3c":{
      "scriptId":"u45"},
    "3b6b9403932744da9cd15770cb8da4e1":{
      "scriptId":"u46"},
    "9ed6504f1bb24c3895a570588d0db943":{
      "scriptId":"u47"},
    "f98b1f7bf1fe454d92b0b5ef53576070":{
      "scriptId":"u48"},
    "f1687d6497734187a5d01fdb84215d4e":{
      "scriptId":"u49"},
    "5ab754a611604a98946427eaedce5170":{
      "scriptId":"u50"},
    "ce67ea38758b45888054e92b3f3607f1":{
      "scriptId":"u51"},
    "66b3c650c0cc4da382d7205218e4b1c3":{
      "scriptId":"u52"},
    "e60e5e86d64f49259116b492f52bc015":{
      "scriptId":"u53"},
    "26dd3a6a6f3440cdbb18496efd6a09b9":{
      "scriptId":"u54"},
    "631e252d9db5491fa15bc060bf36dca5":{
      "scriptId":"u55"},
    "ac877cef1033465e8f96adf8862b5369":{
      "scriptId":"u56"},
    "af9b39e142df4897b3b37d23aac44112":{
      "scriptId":"u57"},
    "ad451ba2a565445ca794b8e475553d22":{
      "scriptId":"u58"},
    "19c40a12917b4d328a39132da82bab96":{
      "scriptId":"u59"},
    "8fb9dff57bc0419bacca932942cdc51f":{
      "scriptId":"u60"},
    "24929ac59c5c44bfb368065e393e2f00":{
      "scriptId":"u61"},
    "1d9a0cc986f949d5ae9200700c02e76a":{
      "scriptId":"u62"},
    "ca2733f429824aa384badf36a26d1411":{
      "scriptId":"u63"},
    "e831dc0559844057b1e969031171b422":{
      "scriptId":"u64"},
    "25639464e7e249b29293ca977df36db2":{
      "scriptId":"u65"},
    "c7dd3dfb851249bcb2da28560650e216":{
      "scriptId":"u66"},
    "7462b2d03e6f4ce5a9a1918fc1c145df":{
      "scriptId":"u67"},
    "e9fd8cf999654a15b21ddbe5578c0f14":{
      "scriptId":"u68"},
    "c4b2606e8dcc40bd825edfc6a684142b":{
      "scriptId":"u69"},
    "7d7e3c9a7ba44b78b7677e14e635a21a":{
      "scriptId":"u70"},
    "8fdc00e30c5f4297a09c6a825fffc315":{
      "scriptId":"u71"},
    "316cb704caa74cd6aa4ba4103dd06b21":{
      "scriptId":"u72"},
    "798f4d432c7c46a3959f1d84335ec4fe":{
      "scriptId":"u73"},
    "01dbed9ebc5b47f6875ad6b352baf239":{
      "scriptId":"u74"},
    "588e6967cac4434fa1a16f8161a0c76b":{
      "scriptId":"u75"},
    "a310e9d442644939b012bf8094267a9b":{
      "scriptId":"u76"},
    "8f2c2c72786f4de6ab9e6308d4eceea2":{
      "scriptId":"u77"},
    "d7d8537532fa44cc9a67d6c72d3b6d3f":{
      "scriptId":"u78"},
    "01a62b5e232f48cbab3a4c4dc00d2a02":{
      "scriptId":"u79"}}});