$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1528362643658.45),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8975f00e91f0479cb4f5a2aa313f81f9",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"483c7db1acd0415e86a4316fef63d1da",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":31,
              "y":115},
            "size":{
              "width":840,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec0ba35fafd240ef8b7c469b375753de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":31,
                  "y":115},
                "size":{
                  "width":840,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"9809a00a366341b69a5cb9c902ed99e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":41,
              "y":124},
            "size":{
              "width":205,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58f22babeabf4401b94fd2995405b760",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":41,
                  "y":124},
                "size":{
                  "width":205,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"1e864087a6f84271bd89313b5c41e2ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":284,
              "y":124},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7fd2cef67a24223bd8b516010ef53c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":284,
                  "y":124},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ed1d6995463b4e90a2d9637607e0d169",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"700"},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"9634a514035f4973b7b7da72ac1d73a3",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":124},
            "size":{
              "width":210,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"705a97fc23d9407fbed8e311c1be388a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":661,
              "y":124},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bd1191059874d749aa1d2a47a46889f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":661,
                  "y":124},
                "size":{
                  "width":100,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"1795a6ed6dea4278966cb40001d94d70",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":124},
            "size":{
              "width":9,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c22383d6bb5b4d2faaeaeaac1c2773fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":760,
                  "y":124},
                "size":{
                  "width":9,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u10.png"}},
{
          "id":"ae24bd52224444de814234aef219b44b",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":757,
              "y":124},
            "size":{
              "width":15,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78c15507412c4da8871a7317e011ee2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":757,
                  "y":124},
                "size":{
                  "width":15,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u12.png"}},
{
          "id":"db9c3f09c2604e34919666b49e239692",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":901,
              "y":115},
            "size":{
              "width":90,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1d1bcdc10874e448719ef89a421f019",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":901,
                  "y":115},
                "size":{
                  "width":90,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"e81c111432be4326bc1bbac97073e053",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":32,
              "y":225},
            "size":{
              "width":840,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99f9d0efbc874afe88383703d586c012",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":32,
                  "y":225},
                "size":{
                  "width":840,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"9f125eda24314cb695cf68b985ec73ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":42,
              "y":234},
            "size":{
              "width":205,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feadf579deea484d8219c27e95215aad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":42,
                  "y":234},
                "size":{
                  "width":205,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"0db2417d936d405e808751c2f5c2a59d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":285,
              "y":234},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9d2e53ec801440d844998a03a2ff2a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":285,
                  "y":234},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9787da3f56dc43b1aa7bbcf8bd338006",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"700"},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"3c010b29ca1441fb93f57b362c04a4a6",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":234},
            "size":{
              "width":210,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"0d60ddfe7a814708a1b6f66f86559fa0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":662,
              "y":234},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9507aa2a3e3b4b2d9fcc1110447f480f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":662,
                  "y":234},
                "size":{
                  "width":100,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u24.png"}},
{
          "id":"4c2a33f2b77341dfb348779317d5b323",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":766,
              "y":235},
            "size":{
              "width":9,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0df392070cf14169b4c09752c60c5c75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":766,
                  "y":235},
                "size":{
                  "width":9,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u10.png"}},
{
          "id":"69714f46928548e28a3e5486d4d52f1e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":763,
              "y":235},
            "size":{
              "width":15,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"314f9d79d6ae4bd18fd094a144768cd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":763,
                  "y":235},
                "size":{
                  "width":15,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u12.png"}},
{
          "id":"599686949e944b488f7d0e40f73b7e82",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":662,
              "y":255},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0e0918d5847449b971710cce42a2970",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":662,
                  "y":255},
                "size":{
                  "width":100,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9ba7c58c36e548be893b96df5c76257f",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 查看用户信息",
                              "target":{
                                "targetType":"page",
                                "url":"查看用户信息.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/首页/u24.png"}},
{
          "id":"fc87edc4eef44121835ea37545758a2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":662,
              "y":276},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f406d041085346a0af1d7f42cd9caae1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":662,
                  "y":276},
                "size":{
                  "width":100,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f52faea3e1e147b892cf972e72b812c7",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 修改用户信息",
                              "target":{
                                "targetType":"page",
                                "url":"修改用户信息.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/首页/u24.png"}},
{
          "id":"4e4b73d3077c4f3ca6d335faa29a9c42",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":662,
              "y":297},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a6f9b4322f942c2b0fc4cd03c372b54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":662,
                  "y":297},
                "size":{
                  "width":100,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"286497edb9964ab08dc4ae3e647ff343",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 修改密码",
                              "target":{
                                "targetType":"page",
                                "url":"修改密码.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/首页/u24.png"}},
{
          "id":"8303d525b9b941d9aac3507cfc559f07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":662,
              "y":318},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b1f4218991a4bffabafbdbbc1714ecb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":662,
                  "y":318},
                "size":{
                  "width":100,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d3bd6e74a596448dba9b36d5fa5c0dc7",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 登出",
                              "target":{
                                "targetType":"page",
                                "url":"登出.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/首页/u24.png"}},
{
          "id":"9b65992a9e40453dbd7318a4e56fb061",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":892,
              "y":225},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7e245ae8c7f401a8468ccdda645cb09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":892,
                  "y":225},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}},
{
          "id":"c4978e393da04784996c695b8905e286",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":32,
              "y":30},
            "size":{
              "width":840,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bc8409284bb4fed8cb5453660044d76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":32,
                  "y":30},
                "size":{
                  "width":840,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"124943e45ea649e184a2eb138e274bb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":42,
              "y":39},
            "size":{
              "width":205,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64d88a564c77465c97be663df0dbaa32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":42,
                  "y":39},
                "size":{
                  "width":205,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"8877531728b846b694134020154559ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":285,
              "y":39},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dea1a21f8bb442599282ce76d1a376a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":285,
                  "y":39},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b67153da04f749a6ac2d0861a3808339",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"700"},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"43ff34285f5a4d9f99a8bf189e092bd6",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":39},
            "size":{
              "width":210,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"d9b191b2f9da4d8ab9957e1aa95ea226",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":662,
              "y":39},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cf7abe3170d4d5aa106c19c2ef64498",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":662,
                  "y":39},
                "size":{
                  "width":100,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"112e66b8dadf4098bdf66d52a6426ffb",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 登录",
                              "target":{
                                "targetType":"page",
                                "url":"登录.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"707a01a2de0d4d29b9d18a979c454b1e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":761,
              "y":39},
            "size":{
              "width":9,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30246105cfac40488c80014f71d820e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":761,
                  "y":39},
                "size":{
                  "width":9,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u10.png"}},
{
          "id":"01a5fa3f477645e7af4560f846b1f641",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":758,
              "y":39},
            "size":{
              "width":15,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"823519c880b44758871348009bb57bce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":758,
                  "y":39},
                "size":{
                  "width":15,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u12.png"}},
{
          "id":"c45be94ceb8549828fd83135062a59aa",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":892,
              "y":30},
            "size":{
              "width":110,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecc9789d927a4babb0bfd11fe6a75d61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":892,
                  "y":30},
                "size":{
                  "width":110,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u59.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "483c7db1acd0415e86a4316fef63d1da":{
      "scriptId":"u0"},
    "ec0ba35fafd240ef8b7c469b375753de":{
      "scriptId":"u1"},
    "9809a00a366341b69a5cb9c902ed99e9":{
      "scriptId":"u2"},
    "58f22babeabf4401b94fd2995405b760":{
      "scriptId":"u3"},
    "1e864087a6f84271bd89313b5c41e2ce":{
      "scriptId":"u4"},
    "e7fd2cef67a24223bd8b516010ef53c1":{
      "scriptId":"u5"},
    "ed1d6995463b4e90a2d9637607e0d169":{
      "scriptId":"u6"},
    "9634a514035f4973b7b7da72ac1d73a3":{
      "scriptId":"u7"},
    "705a97fc23d9407fbed8e311c1be388a":{
      "scriptId":"u8"},
    "0bd1191059874d749aa1d2a47a46889f":{
      "scriptId":"u9"},
    "1795a6ed6dea4278966cb40001d94d70":{
      "scriptId":"u10"},
    "c22383d6bb5b4d2faaeaeaac1c2773fc":{
      "scriptId":"u11"},
    "ae24bd52224444de814234aef219b44b":{
      "scriptId":"u12"},
    "78c15507412c4da8871a7317e011ee2e":{
      "scriptId":"u13"},
    "db9c3f09c2604e34919666b49e239692":{
      "scriptId":"u14"},
    "c1d1bcdc10874e448719ef89a421f019":{
      "scriptId":"u15"},
    "e81c111432be4326bc1bbac97073e053":{
      "scriptId":"u16"},
    "99f9d0efbc874afe88383703d586c012":{
      "scriptId":"u17"},
    "9f125eda24314cb695cf68b985ec73ef":{
      "scriptId":"u18"},
    "feadf579deea484d8219c27e95215aad":{
      "scriptId":"u19"},
    "0db2417d936d405e808751c2f5c2a59d":{
      "scriptId":"u20"},
    "e9d2e53ec801440d844998a03a2ff2a3":{
      "scriptId":"u21"},
    "9787da3f56dc43b1aa7bbcf8bd338006":{
      "scriptId":"u22"},
    "3c010b29ca1441fb93f57b362c04a4a6":{
      "scriptId":"u23"},
    "0d60ddfe7a814708a1b6f66f86559fa0":{
      "scriptId":"u24"},
    "9507aa2a3e3b4b2d9fcc1110447f480f":{
      "scriptId":"u25"},
    "4c2a33f2b77341dfb348779317d5b323":{
      "scriptId":"u26"},
    "0df392070cf14169b4c09752c60c5c75":{
      "scriptId":"u27"},
    "69714f46928548e28a3e5486d4d52f1e":{
      "scriptId":"u28"},
    "314f9d79d6ae4bd18fd094a144768cd1":{
      "scriptId":"u29"},
    "599686949e944b488f7d0e40f73b7e82":{
      "scriptId":"u30"},
    "b0e0918d5847449b971710cce42a2970":{
      "scriptId":"u31"},
    "9ba7c58c36e548be893b96df5c76257f":{
      "scriptId":"u32"},
    "fc87edc4eef44121835ea37545758a2f":{
      "scriptId":"u33"},
    "f406d041085346a0af1d7f42cd9caae1":{
      "scriptId":"u34"},
    "f52faea3e1e147b892cf972e72b812c7":{
      "scriptId":"u35"},
    "4e4b73d3077c4f3ca6d335faa29a9c42":{
      "scriptId":"u36"},
    "2a6f9b4322f942c2b0fc4cd03c372b54":{
      "scriptId":"u37"},
    "286497edb9964ab08dc4ae3e647ff343":{
      "scriptId":"u38"},
    "8303d525b9b941d9aac3507cfc559f07":{
      "scriptId":"u39"},
    "3b1f4218991a4bffabafbdbbc1714ecb":{
      "scriptId":"u40"},
    "d3bd6e74a596448dba9b36d5fa5c0dc7":{
      "scriptId":"u41"},
    "9b65992a9e40453dbd7318a4e56fb061":{
      "scriptId":"u42"},
    "b7e245ae8c7f401a8468ccdda645cb09":{
      "scriptId":"u43"},
    "c4978e393da04784996c695b8905e286":{
      "scriptId":"u44"},
    "4bc8409284bb4fed8cb5453660044d76":{
      "scriptId":"u45"},
    "124943e45ea649e184a2eb138e274bb1":{
      "scriptId":"u46"},
    "64d88a564c77465c97be663df0dbaa32":{
      "scriptId":"u47"},
    "8877531728b846b694134020154559ef":{
      "scriptId":"u48"},
    "dea1a21f8bb442599282ce76d1a376a9":{
      "scriptId":"u49"},
    "b67153da04f749a6ac2d0861a3808339":{
      "scriptId":"u50"},
    "43ff34285f5a4d9f99a8bf189e092bd6":{
      "scriptId":"u51"},
    "d9b191b2f9da4d8ab9957e1aa95ea226":{
      "scriptId":"u52"},
    "3cf7abe3170d4d5aa106c19c2ef64498":{
      "scriptId":"u53"},
    "112e66b8dadf4098bdf66d52a6426ffb":{
      "scriptId":"u54"},
    "707a01a2de0d4d29b9d18a979c454b1e":{
      "scriptId":"u55"},
    "30246105cfac40488c80014f71d820e3":{
      "scriptId":"u56"},
    "01a5fa3f477645e7af4560f846b1f641":{
      "scriptId":"u57"},
    "823519c880b44758871348009bb57bce":{
      "scriptId":"u58"},
    "c45be94ceb8549828fd83135062a59aa":{
      "scriptId":"u59"},
    "ecc9789d927a4babb0bfd11fe6a75d61":{
      "scriptId":"u60"}}});