$axure.loadCurrentPage({
  "url":"编辑课程.html",
  "generationDate":new Date(1528362642772.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"db43af2bf5d04c9e92f379c380ec9ce0",
    "type":"Axure:Page",
    "name":"编辑课程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d33b85c400724fdf8b22c21ea362e5b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":430},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"582d3747f2a44494bc62ffe03343199d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":430},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1076b2ceaf7648bbbdf1423202cf94d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":480},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a5101f203e64ed68c064a33bb462b9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":480},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71769106b9ef44c093607cd019519de7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":536},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"667891bd08d742189f81a497bfdc758c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":536},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5378f16966b0481abe044dce7112c362",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":596},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5a0442780b54a73babfc6a6a8d945fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":596},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"175ff486ce704a07b092c1b5902771df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":666},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b99be3fb73f04e8596e614503644dfa0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":666},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24c0b43bc132445784edfd40b91170af",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":132,
              "y":663},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"f8371af074bc4bbf96ce0393fcee7fd7",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":132,
              "y":596},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"52ed0ce7b4be48d9bbaad328b7241e59",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":132,
              "y":534},
            "size":{
              "width":120,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79fea089c8bc4c5099d66222cc48c647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":132,
                  "y":534},
                "size":{
                  "width":120,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加课程/u12.png"}},
{
          "id":"064cc0948c4e4bfc9ed037b8e0426f80",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":132,
              "y":480},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cbacce462944b09abe6167cd81b3ec2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":132,
                  "y":480},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加课程/u14.png"}},
{
          "id":"6a98221a1e82442896c9db660abef5dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":132,
              "y":430},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad4b34423e0346ce81a04b6a10ddcfd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":132,
                  "y":430},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加课程/u14.png"}},
{
          "id":"ddff6b6077a84b2486c06cd4470174e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":262,
              "y":596},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c0d8ff4529540e092054b9e7ae0fdfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":262,
                  "y":596},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加课程/u18.png"}},
{
          "id":"0987111a943641799ee28098627fdcc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":267,
              "y":666},
            "size":{
              "width":185,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d11cf3d9e50449e8399fb7c3e7fd987",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":267,
                  "y":666},
                "size":{
                  "width":185,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加课程/u20.png"}},
{
          "id":"70275a377070405696d535d6b2adb7a9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":731},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1c49a74eecad4357b08b121065e0ad2d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":182,
              "y":731},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e738c069546043cbb3164628962d721d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":242,
              "y":746},
            "size":{
              "width":170,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28a9eb46a28d47faa981210996a54967",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":242,
                  "y":746},
                "size":{
                  "width":170,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加课程/u24.png"}},
{
          "id":"a67bc7ad7eb9456db0c779d9742327dd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":390},
            "size":{
              "width":1040,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/编辑课程/u26_line.png"}},
{
          "id":"6e2fa49be47d45b2b767a09e95bdefd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":40,
              "y":30},
            "size":{
              "width":1003,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3aa899ba2fb74974b5e7470807450b84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":40,
                  "y":30},
                "size":{
                  "width":1003,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u27.png"}},
{
          "id":"31ef84461a034d74ad42b004050c8f85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":37},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d205620902942058b757ad10cb05a43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66,
                  "y":37},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"871790544f70410abb12bb93a984f0fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":143,
              "y":37},
            "size":{
              "width":141,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee26a7ce66cd4032b566695680d1e58c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":143,
                  "y":37},
                "size":{
                  "width":141,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u31.png"}},
{
          "id":"6e22104f9bc64e769802ea52325a65a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":927,
              "y":37},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"815987131a45424f9b2eeac62133d1d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":927,
                  "y":37},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u33.png"}},
{
          "id":"3aab7363d8a04db59cdf73608ddd0a00",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":60},
            "size":{
              "width":1003,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23543b4e307342029db7f096549f34de",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9f21e9e3bd4e42a3a1996ebad529982b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u15.png"}},
{
              "id":"b4d56edff5914fc7a71f037fbd183f5b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b0c8b5a9716343b0a5e27788c1acc5ca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"e6d9e05285d941e38af91040ad99ff09",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eeec293257644be0b849eb30945e7653",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"318f70c0ee384db5b6d3550d09f0378f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"13b19b29bebc40b8850dda34b1bdc3ca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u15.png"}},
{
              "id":"862945786269484b9cf29e7ab708428d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"19f0cd7167334e52b2c6260fe0c645dc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"e94b32ad23bb41429833090367a5d304",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0d361be3800a45c6bd68ae301163cf14",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"4988a1275bf1416f8c7f52ab98db7fc6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"abe30607391040959c6d713bfb3c6dfd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u15.png"}},
{
              "id":"c85bdbab1e6246bab5c9fcc23faf0d72",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"318226e367934398b67f3d03ba12ca8b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"18cebc4547fe479fa0201b6b563934e6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6d840a4c1387414abdf9b35c897be5aa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"1def42da659a494b8f32ea394ee66874",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":119,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a7a543c3632847dcb5b66c2366852507",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":119,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u74.png"}},
{
              "id":"0fe44f405ba245e7a1cd7c6f93ed0626",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":36},
                "size":{
                  "width":119,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"509befe9e63a44d8bef47486da87d464",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":36},
                    "size":{
                      "width":119,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u88.png"}},
{
              "id":"35548db4e00c4bcbaee66ef9d47684b5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":66},
                "size":{
                  "width":119,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fa6ae9a5b51f4f969035e70de7389664",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":66},
                    "size":{
                      "width":119,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u103.png"}},
{
              "id":"0540bb8aaa374d00a077f238099295e8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":555,
                  "y":0},
                "size":{
                  "width":117,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f52e21e6269348b0ba978a2cc9417b7f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":555,
                      "y":0},
                    "size":{
                      "width":117,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u78.png"}},
{
              "id":"354e402a99744e5bb07053db670cf3f5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":555,
                  "y":36},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7f7a57a564744b66a28d4bcaa9269b14",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":555,
                      "y":36},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u92.png"}},
{
              "id":"e622aa87290f448a81ed27d4a1b670a0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":555,
                  "y":66},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1f434c9ac2324b2a81ba1643a3908a9c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":555,
                      "y":66},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u107.png"}},
{
              "id":"bc943d4d60554d4bbcab8953e1cfabfa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":419,
                  "y":0},
                "size":{
                  "width":136,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"78ba722940764015b44f562bbaedb50a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":419,
                      "y":0},
                    "size":{
                      "width":136,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u76.png"}},
{
              "id":"cb45b577d9f34bd097aa00620c3e4136",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":419,
                  "y":36},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2c4f5f29642d4a16b9b4492a30dbf3d5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":419,
                      "y":36},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u90.png"}},
{
              "id":"198aa5d17e8149198cbe0aa198752044",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":419,
                  "y":66},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1f34b1ac30ef4035adc647eeb24f0ae3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":419,
                      "y":66},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u105.png"}},
{
              "id":"16a15151c22144359664663c377d4d5c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":783,
                  "y":0},
                "size":{
                  "width":108,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5b6c9e1f97a141e994ceef59e167ec91",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":783,
                      "y":0},
                    "size":{
                      "width":108,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑课程/u50.png"}},
{
              "id":"d01d3db2b058427f942620915fb5b3f4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":783,
                  "y":36},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"be5ef7cc65d7499ab0c54f8d17defaa3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":783,
                      "y":36},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"636065acf72e4df682f0d1b3ff670928",
                      "label":"",
                      "type":"hyperlink",
                      "styleType":"hyperlink",
                      "visible":true,
                      "style":{
},
                      "adaptiveStyles":{
},
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 编辑课程",
                                  "target":{
                                    "targetType":"page",
                                    "url":"编辑课程.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true}]}],
              "images":{
                "normal~":"images/编辑课程/u68.png"}},
{
              "id":"17970ff5ae054bbb9a88b52ace41e050",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":783,
                  "y":66},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"587a19677e1e4132b49d5c4caa59fd44",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":783,
                      "y":66},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"624c839d9f7e442283fefd495a05ee00",
                      "label":"",
                      "type":"hyperlink",
                      "styleType":"hyperlink",
                      "visible":true,
                      "style":{
},
                      "adaptiveStyles":{
},
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 编辑课程",
                                  "target":{
                                    "targetType":"page",
                                    "url":"编辑课程.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true}]}],
              "images":{
                "normal~":"images/编辑课程/u88.png"}},
{
              "id":"54acf1695f234d43bbb685b170266dc6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":891,
                  "y":0},
                "size":{
                  "width":112,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1ec830c36e764a8ea1913874837cc866",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":891,
                      "y":0},
                    "size":{
                      "width":112,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑课程/u52.png"}},
{
              "id":"d9e7402dc6284bceac597efca1bffc2f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":891,
                  "y":36},
                "size":{
                  "width":112,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"128e8d5c204f46eda20f8a2d92876f4c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":891,
                      "y":36},
                    "size":{
                      "width":112,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3591da82e76c44e78b0a7df0dfd91493",
                      "label":"",
                      "type":"hyperlink",
                      "styleType":"hyperlink",
                      "visible":true,
                      "style":{
},
                      "adaptiveStyles":{
},
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 链接",
                                  "target":{
                                    "targetType":"page",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true}]}],
              "images":{
                "normal~":"images/编辑课程/u71.png"}},
{
              "id":"acaacc179bf048e3941a99aac6f25d86",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":891,
                  "y":66},
                "size":{
                  "width":112,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"80f2b459eca646d881c4f9c60fe650e6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":891,
                      "y":66},
                    "size":{
                      "width":112,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"71a60c0538fc49e8af754df79f43afeb",
                      "label":"",
                      "type":"hyperlink",
                      "styleType":"hyperlink",
                      "visible":true,
                      "style":{
},
                      "adaptiveStyles":{
},
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 链接",
                                  "target":{
                                    "targetType":"page",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true}]}],
              "images":{
                "normal~":"images/编辑课程/u91.png"}},
{
              "id":"ab033bff61ab49809d98166cf8c1bb80",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":672,
                  "y":0},
                "size":{
                  "width":111,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"56efaa45d6624bfe8fc91bf4336f6d82",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":672,
                      "y":0},
                    "size":{
                      "width":111,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑课程/u48.png"}},
{
              "id":"30004ebae54e46c3a2c29295fd70dda6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":672,
                  "y":36},
                "size":{
                  "width":111,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d2369c5c3ed04ce5a5e084280f4d3a7c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":672,
                      "y":36},
                    "size":{
                      "width":111,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑课程/u66.png"}},
{
              "id":"5b1993ea5f464838ab3f110cce91f698",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":672,
                  "y":66},
                "size":{
                  "width":111,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a6af22a14d5a4f45af0e57f9e13223b5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":672,
                      "y":66},
                    "size":{
                      "width":111,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑课程/u86.png"}}]},
{
          "id":"3c454b9f73974b829c30304d9c857e64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":40,
              "y":156},
            "size":{
              "width":1003,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc88c6dde89142e1b1ce19a308265319",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":40,
                  "y":156},
                "size":{
                  "width":1003,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u27.png"}},
{
          "id":"6507a7d4865c45669d83fd22083dd8ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":163},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"450cf79c67c0406cb7d7a4c1423e910a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66,
                  "y":163},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1334d17c003b49c68043ceb12cd26c14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":143,
              "y":163},
            "size":{
              "width":141,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a002f79d62b944f68e4ad2ab405273a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":143,
                  "y":163},
                "size":{
                  "width":141,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u31.png"}},
{
          "id":"0a63f0366a4748d0a0d2e1e26e3561af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":927,
              "y":163},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b981d46c35284a838fd8d9824a8e0db9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":927,
                  "y":163},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u33.png"}},
{
          "id":"0d61a6fb3787416f91349c4c304eb34b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":40,
              "y":186},
            "size":{
              "width":1003,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"634df365d67a41c4b480bb8763a26569",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":40,
                  "y":186},
                "size":{
                  "width":1003,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u27.png"}},
{
          "id":"43ee3a56d13043bdb63040d7acaf98da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":193},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6bdfdf5e990475e92aaf2b3cf8c9e3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66,
                  "y":193},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2de5f86032234c8b9795247262214c1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":143,
              "y":193},
            "size":{
              "width":141,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c82b29e1f2b84070afa06a036977a31a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":143,
                  "y":193},
                "size":{
                  "width":141,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u31.png"}},
{
          "id":"0af3aaf0c8ec4a09af3c6696c9e95cba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":927,
              "y":193},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b4423d8e11145e485c2d1696c605840",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":927,
                  "y":193},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u33.png"}},
{
          "id":"49e87ef9559c49ce8597d79dc25ebc83",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":40,
              "y":216},
            "size":{
              "width":1003,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23bcd8362e224154b3969ec43daa36f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":40,
                  "y":216},
                "size":{
                  "width":1003,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u27.png"}},
{
          "id":"09e12672d66140d5a8dae5c7aab6ec84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":223},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e25718fbff641c188141b68b458f251",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66,
                  "y":223},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7a472b5e3324431ac499ca15d313c91",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":143,
              "y":223},
            "size":{
              "width":141,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7208b34639b4c2a95b81cac0c9a475a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":143,
                  "y":223},
                "size":{
                  "width":141,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u31.png"}},
{
          "id":"fcb4a353605c469a9676283717d7e71f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":927,
              "y":223},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc4e34ecfb9a4befacbcf0cbd6234ead",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":927,
                  "y":223},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u33.png"}},
{
          "id":"81291edbdd9b43a6b609bc726ca63a72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":40,
              "y":256},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af292148626d4d40b26dc0330ead40c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":40,
                  "y":256},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u112.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d33b85c400724fdf8b22c21ea362e5b2":{
      "scriptId":"u0"},
    "582d3747f2a44494bc62ffe03343199d":{
      "scriptId":"u1"},
    "1076b2ceaf7648bbbdf1423202cf94d3":{
      "scriptId":"u2"},
    "8a5101f203e64ed68c064a33bb462b9f":{
      "scriptId":"u3"},
    "71769106b9ef44c093607cd019519de7":{
      "scriptId":"u4"},
    "667891bd08d742189f81a497bfdc758c":{
      "scriptId":"u5"},
    "5378f16966b0481abe044dce7112c362":{
      "scriptId":"u6"},
    "d5a0442780b54a73babfc6a6a8d945fc":{
      "scriptId":"u7"},
    "175ff486ce704a07b092c1b5902771df":{
      "scriptId":"u8"},
    "b99be3fb73f04e8596e614503644dfa0":{
      "scriptId":"u9"},
    "24c0b43bc132445784edfd40b91170af":{
      "scriptId":"u10"},
    "f8371af074bc4bbf96ce0393fcee7fd7":{
      "scriptId":"u11"},
    "52ed0ce7b4be48d9bbaad328b7241e59":{
      "scriptId":"u12"},
    "79fea089c8bc4c5099d66222cc48c647":{
      "scriptId":"u13"},
    "064cc0948c4e4bfc9ed037b8e0426f80":{
      "scriptId":"u14"},
    "8cbacce462944b09abe6167cd81b3ec2":{
      "scriptId":"u15"},
    "6a98221a1e82442896c9db660abef5dc":{
      "scriptId":"u16"},
    "ad4b34423e0346ce81a04b6a10ddcfd3":{
      "scriptId":"u17"},
    "ddff6b6077a84b2486c06cd4470174e9":{
      "scriptId":"u18"},
    "6c0d8ff4529540e092054b9e7ae0fdfe":{
      "scriptId":"u19"},
    "0987111a943641799ee28098627fdcc4":{
      "scriptId":"u20"},
    "9d11cf3d9e50449e8399fb7c3e7fd987":{
      "scriptId":"u21"},
    "70275a377070405696d535d6b2adb7a9":{
      "scriptId":"u22"},
    "1c49a74eecad4357b08b121065e0ad2d":{
      "scriptId":"u23"},
    "e738c069546043cbb3164628962d721d":{
      "scriptId":"u24"},
    "28a9eb46a28d47faa981210996a54967":{
      "scriptId":"u25"},
    "a67bc7ad7eb9456db0c779d9742327dd":{
      "scriptId":"u26"},
    "6e2fa49be47d45b2b767a09e95bdefd8":{
      "scriptId":"u27"},
    "3aa899ba2fb74974b5e7470807450b84":{
      "scriptId":"u28"},
    "31ef84461a034d74ad42b004050c8f85":{
      "scriptId":"u29"},
    "2d205620902942058b757ad10cb05a43":{
      "scriptId":"u30"},
    "871790544f70410abb12bb93a984f0fd":{
      "scriptId":"u31"},
    "ee26a7ce66cd4032b566695680d1e58c":{
      "scriptId":"u32"},
    "6e22104f9bc64e769802ea52325a65a9":{
      "scriptId":"u33"},
    "815987131a45424f9b2eeac62133d1d9":{
      "scriptId":"u34"},
    "3aab7363d8a04db59cdf73608ddd0a00":{
      "scriptId":"u35"},
    "23543b4e307342029db7f096549f34de":{
      "scriptId":"u36"},
    "9f21e9e3bd4e42a3a1996ebad529982b":{
      "scriptId":"u37"},
    "318f70c0ee384db5b6d3550d09f0378f":{
      "scriptId":"u38"},
    "13b19b29bebc40b8850dda34b1bdc3ca":{
      "scriptId":"u39"},
    "4988a1275bf1416f8c7f52ab98db7fc6":{
      "scriptId":"u40"},
    "abe30607391040959c6d713bfb3c6dfd":{
      "scriptId":"u41"},
    "1def42da659a494b8f32ea394ee66874":{
      "scriptId":"u42"},
    "a7a543c3632847dcb5b66c2366852507":{
      "scriptId":"u43"},
    "bc943d4d60554d4bbcab8953e1cfabfa":{
      "scriptId":"u44"},
    "78ba722940764015b44f562bbaedb50a":{
      "scriptId":"u45"},
    "0540bb8aaa374d00a077f238099295e8":{
      "scriptId":"u46"},
    "f52e21e6269348b0ba978a2cc9417b7f":{
      "scriptId":"u47"},
    "ab033bff61ab49809d98166cf8c1bb80":{
      "scriptId":"u48"},
    "56efaa45d6624bfe8fc91bf4336f6d82":{
      "scriptId":"u49"},
    "16a15151c22144359664663c377d4d5c":{
      "scriptId":"u50"},
    "5b6c9e1f97a141e994ceef59e167ec91":{
      "scriptId":"u51"},
    "54acf1695f234d43bbb685b170266dc6":{
      "scriptId":"u52"},
    "1ec830c36e764a8ea1913874837cc866":{
      "scriptId":"u53"},
    "b4d56edff5914fc7a71f037fbd183f5b":{
      "scriptId":"u54"},
    "b0c8b5a9716343b0a5e27788c1acc5ca":{
      "scriptId":"u55"},
    "862945786269484b9cf29e7ab708428d":{
      "scriptId":"u56"},
    "19f0cd7167334e52b2c6260fe0c645dc":{
      "scriptId":"u57"},
    "c85bdbab1e6246bab5c9fcc23faf0d72":{
      "scriptId":"u58"},
    "318226e367934398b67f3d03ba12ca8b":{
      "scriptId":"u59"},
    "0fe44f405ba245e7a1cd7c6f93ed0626":{
      "scriptId":"u60"},
    "509befe9e63a44d8bef47486da87d464":{
      "scriptId":"u61"},
    "cb45b577d9f34bd097aa00620c3e4136":{
      "scriptId":"u62"},
    "2c4f5f29642d4a16b9b4492a30dbf3d5":{
      "scriptId":"u63"},
    "354e402a99744e5bb07053db670cf3f5":{
      "scriptId":"u64"},
    "7f7a57a564744b66a28d4bcaa9269b14":{
      "scriptId":"u65"},
    "30004ebae54e46c3a2c29295fd70dda6":{
      "scriptId":"u66"},
    "d2369c5c3ed04ce5a5e084280f4d3a7c":{
      "scriptId":"u67"},
    "d01d3db2b058427f942620915fb5b3f4":{
      "scriptId":"u68"},
    "be5ef7cc65d7499ab0c54f8d17defaa3":{
      "scriptId":"u69"},
    "636065acf72e4df682f0d1b3ff670928":{
      "scriptId":"u70"},
    "d9e7402dc6284bceac597efca1bffc2f":{
      "scriptId":"u71"},
    "128e8d5c204f46eda20f8a2d92876f4c":{
      "scriptId":"u72"},
    "3591da82e76c44e78b0a7df0dfd91493":{
      "scriptId":"u73"},
    "e6d9e05285d941e38af91040ad99ff09":{
      "scriptId":"u74"},
    "eeec293257644be0b849eb30945e7653":{
      "scriptId":"u75"},
    "e94b32ad23bb41429833090367a5d304":{
      "scriptId":"u76"},
    "0d361be3800a45c6bd68ae301163cf14":{
      "scriptId":"u77"},
    "18cebc4547fe479fa0201b6b563934e6":{
      "scriptId":"u78"},
    "6d840a4c1387414abdf9b35c897be5aa":{
      "scriptId":"u79"},
    "35548db4e00c4bcbaee66ef9d47684b5":{
      "scriptId":"u80"},
    "fa6ae9a5b51f4f969035e70de7389664":{
      "scriptId":"u81"},
    "198aa5d17e8149198cbe0aa198752044":{
      "scriptId":"u82"},
    "1f34b1ac30ef4035adc647eeb24f0ae3":{
      "scriptId":"u83"},
    "e622aa87290f448a81ed27d4a1b670a0":{
      "scriptId":"u84"},
    "1f434c9ac2324b2a81ba1643a3908a9c":{
      "scriptId":"u85"},
    "5b1993ea5f464838ab3f110cce91f698":{
      "scriptId":"u86"},
    "a6af22a14d5a4f45af0e57f9e13223b5":{
      "scriptId":"u87"},
    "17970ff5ae054bbb9a88b52ace41e050":{
      "scriptId":"u88"},
    "587a19677e1e4132b49d5c4caa59fd44":{
      "scriptId":"u89"},
    "624c839d9f7e442283fefd495a05ee00":{
      "scriptId":"u90"},
    "acaacc179bf048e3941a99aac6f25d86":{
      "scriptId":"u91"},
    "80f2b459eca646d881c4f9c60fe650e6":{
      "scriptId":"u92"},
    "71a60c0538fc49e8af754df79f43afeb":{
      "scriptId":"u93"},
    "3c454b9f73974b829c30304d9c857e64":{
      "scriptId":"u94"},
    "cc88c6dde89142e1b1ce19a308265319":{
      "scriptId":"u95"},
    "6507a7d4865c45669d83fd22083dd8ca":{
      "scriptId":"u96"},
    "450cf79c67c0406cb7d7a4c1423e910a":{
      "scriptId":"u97"},
    "1334d17c003b49c68043ceb12cd26c14":{
      "scriptId":"u98"},
    "a002f79d62b944f68e4ad2ab405273a0":{
      "scriptId":"u99"},
    "0a63f0366a4748d0a0d2e1e26e3561af":{
      "scriptId":"u100"},
    "b981d46c35284a838fd8d9824a8e0db9":{
      "scriptId":"u101"},
    "0d61a6fb3787416f91349c4c304eb34b":{
      "scriptId":"u102"},
    "634df365d67a41c4b480bb8763a26569":{
      "scriptId":"u103"},
    "43ee3a56d13043bdb63040d7acaf98da":{
      "scriptId":"u104"},
    "e6bdfdf5e990475e92aaf2b3cf8c9e3f":{
      "scriptId":"u105"},
    "2de5f86032234c8b9795247262214c1d":{
      "scriptId":"u106"},
    "c82b29e1f2b84070afa06a036977a31a":{
      "scriptId":"u107"},
    "0af3aaf0c8ec4a09af3c6696c9e95cba":{
      "scriptId":"u108"},
    "3b4423d8e11145e485c2d1696c605840":{
      "scriptId":"u109"},
    "49e87ef9559c49ce8597d79dc25ebc83":{
      "scriptId":"u110"},
    "23bcd8362e224154b3969ec43daa36f0":{
      "scriptId":"u111"},
    "09e12672d66140d5a8dae5c7aab6ec84":{
      "scriptId":"u112"},
    "9e25718fbff641c188141b68b458f251":{
      "scriptId":"u113"},
    "b7a472b5e3324431ac499ca15d313c91":{
      "scriptId":"u114"},
    "e7208b34639b4c2a95b81cac0c9a475a":{
      "scriptId":"u115"},
    "fcb4a353605c469a9676283717d7e71f":{
      "scriptId":"u116"},
    "cc4e34ecfb9a4befacbcf0cbd6234ead":{
      "scriptId":"u117"},
    "81291edbdd9b43a6b609bc726ca63a72":{
      "scriptId":"u118"},
    "af292148626d4d40b26dc0330ead40c0":{
      "scriptId":"u119"}}});