$axure.loadCurrentPage({
  "url":"删除课程.html",
  "generationDate":new Date(1528362642960.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bd46b147c7d74cc28c47f487550bcac5",
    "type":"Axure:Page",
    "name":"删除课程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5ac7ca50afec401283c78995e36e47a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":40,
              "y":70},
            "size":{
              "width":1003,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4115d4a10cb5414b9925ee4f270e5f76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":40,
                  "y":70},
                "size":{
                  "width":1003,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u27.png"}},
{
          "id":"b0c2f09d62994efb86a345ccbd7e141a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":77},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"187539442dfb44bd85d233039abc8ea1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66,
                  "y":77},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"336922bb50934f6f9beb097d7b42cae6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":143,
              "y":77},
            "size":{
              "width":141,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67ba68987f6742cf82df8c5a163a8a39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":143,
                  "y":77},
                "size":{
                  "width":141,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u31.png"}},
{
          "id":"a4949ab41e8840eda77fc9bbd7a5c4dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":927,
              "y":77},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b172df1eee464f2c915c0620d2c7f626",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":927,
                  "y":77},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u33.png"}},
{
          "id":"e255d42cc2714587a6999b987a62dc92",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":100},
            "size":{
              "width":1003,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efd1a6e970cc493f803edd3fd6c31970",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"453d1e8a9af648758e4344d2acfb32b6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u15.png"}},
{
              "id":"57c2a61cc9c34ccb937268e3eb55effc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"61149db1e31a4013b24cb1dabf608aa6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"d0844b231efd4545b619c81c5d28ca42",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0b77df7d8df54de4b3a6c778d5f5eccf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"abf436614cc74054b53554a08a8cc281",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9586b8e4af0c4df2816ca1604e21c4cd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u15.png"}},
{
              "id":"b6d3f662f2fe46c3914e4229d623436c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"44fd638279ee46999aaa17435f07dc50",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"33adbcb5923b4d89871b5e4e04327fc8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a173b59e0c68439a94360539e9f249cc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"da66fa45f5444428bc88c0a30d0385a4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5e0cdc9855364a05805f9b1fbfc66fc2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/u15.png"}},
{
              "id":"eaf7713c54f94122af6c5a9427f97865",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":36},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"928d969a07c747a69c55a3f6c2b06bbb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u6.png"}},
{
              "id":"afb115599ffe422f9ea9c03247f9f47f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3abdb2df59b4476ba3bb3944f64a9917",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选课/u23.png"}},
{
              "id":"e04a86639518462fb5c60a5907bf2665",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":119,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d6b9bf0b17ac4e30918635c0e937b7e7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":119,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u74.png"}},
{
              "id":"f52370934d734488b61e14230176265f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":36},
                "size":{
                  "width":119,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6caa7272743e4599bc7b4e810c51b7fa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":36},
                    "size":{
                      "width":119,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u88.png"}},
{
              "id":"c5e1dbd9778d41329d6a4cc7bcab45cc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":66},
                "size":{
                  "width":119,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b429f0ba51f644eb8b555eb21aed4463",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":66},
                    "size":{
                      "width":119,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u103.png"}},
{
              "id":"2acc6652aa0c4732858ccb5a2469788f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":555,
                  "y":0},
                "size":{
                  "width":117,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aee135b497944e4090618d33e80f5ecc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":555,
                      "y":0},
                    "size":{
                      "width":117,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u78.png"}},
{
              "id":"3b94f606061a46d09161eb5a6b758deb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":555,
                  "y":36},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"41c2117fff584b6e8ce8f7281275e0e7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":555,
                      "y":36},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u92.png"}},
{
              "id":"85859f87ac1843458417d10bc4ba9864",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":555,
                  "y":66},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0c4b24d8fdaf491ca6dcd9572d7589b3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":555,
                      "y":66},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u107.png"}},
{
              "id":"79362c5a25f24cc68ffd7af3e76200b8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":419,
                  "y":0},
                "size":{
                  "width":136,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"85d9f814c9bd47cebd7bc21eaccfd2e9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":419,
                      "y":0},
                    "size":{
                      "width":136,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u76.png"}},
{
              "id":"3dd326ab4778404bbb038305f2e6a5ff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":419,
                  "y":36},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"39a98ee1452a45cab8d92e570a05ec48",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":419,
                      "y":36},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u90.png"}},
{
              "id":"11b874d1763e48788b4959b42ac27f93",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":419,
                  "y":66},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0ec8b881b9f3454d9fd941a7c74ecf82",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":419,
                      "y":66},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u105.png"}},
{
              "id":"cfca8514deef4f38984ad14f33da4fc3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":783,
                  "y":0},
                "size":{
                  "width":108,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4c560a25648f46089c4de78c59e7db58",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":783,
                      "y":0},
                    "size":{
                      "width":108,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑课程/u50.png"}},
{
              "id":"82fa30b62ce54acbb2823234b53e2431",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":783,
                  "y":36},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2c72fafcf0844834ae490572d4d6c853",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":783,
                      "y":36},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0707f34f8fff43f6a736706b67c305e6",
                      "label":"",
                      "type":"hyperlink",
                      "styleType":"hyperlink",
                      "visible":true,
                      "style":{
},
                      "adaptiveStyles":{
},
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 编辑课程",
                                  "target":{
                                    "targetType":"page",
                                    "url":"编辑课程.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true}]}],
              "images":{
                "normal~":"images/编辑课程/u68.png"}},
{
              "id":"175ce6da00c64558826cc4374b5000b1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":783,
                  "y":66},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bea157edd96e4226800fb706a0e75e7c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":783,
                      "y":66},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"791a9ed6e46f4b2dafd5754d95ec749c",
                      "label":"",
                      "type":"hyperlink",
                      "styleType":"hyperlink",
                      "visible":true,
                      "style":{
},
                      "adaptiveStyles":{
},
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 编辑课程",
                                  "target":{
                                    "targetType":"page",
                                    "url":"编辑课程.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true}]}],
              "images":{
                "normal~":"images/编辑课程/u88.png"}},
{
              "id":"dc51b5394c3444a4ac02b9f75612feab",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":891,
                  "y":0},
                "size":{
                  "width":112,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"196d7bb77ff2439b8bde8fec74935c26",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":891,
                      "y":0},
                    "size":{
                      "width":112,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑课程/u52.png"}},
{
              "id":"9d54da4f33024de1ae226a6df8abd83f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":891,
                  "y":36},
                "size":{
                  "width":112,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a604cb1114724370a55b8c8a6e741df6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":891,
                      "y":36},
                    "size":{
                      "width":112,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c9431e4624fc476bb4c3f92a65d57701",
                      "label":"",
                      "type":"hyperlink",
                      "styleType":"hyperlink",
                      "visible":true,
                      "style":{
},
                      "adaptiveStyles":{
},
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 链接",
                                  "target":{
                                    "targetType":"page",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true}]}],
              "images":{
                "normal~":"images/编辑课程/u71.png"}},
{
              "id":"8aeaf66cc8c240e7a14c0203f69ee1d0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":891,
                  "y":66},
                "size":{
                  "width":112,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"26d1d2f6284c4c60aaeac097941beff0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":891,
                      "y":66},
                    "size":{
                      "width":112,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"06177637686f4223bcbb1eb6754d66bf",
                      "label":"",
                      "type":"hyperlink",
                      "styleType":"hyperlink",
                      "visible":true,
                      "style":{
},
                      "adaptiveStyles":{
},
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 链接",
                                  "target":{
                                    "targetType":"page",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true}]}],
              "images":{
                "normal~":"images/编辑课程/u91.png"}},
{
              "id":"b397eaaa11d94d71913ab0cafc4adc43",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":672,
                  "y":0},
                "size":{
                  "width":111,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a1d5cfa24d454b78988b07624bdf408c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":672,
                      "y":0},
                    "size":{
                      "width":111,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑课程/u48.png"}},
{
              "id":"1449e13843054a9488421f8a911d02fc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":672,
                  "y":36},
                "size":{
                  "width":111,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"39b0b5c609364e5cb0f31c081793be13",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":672,
                      "y":36},
                    "size":{
                      "width":111,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑课程/u66.png"}},
{
              "id":"6989eb88966849c891aeb8856dd5149b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":672,
                  "y":66},
                "size":{
                  "width":111,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"56e6f4785d814326a026ae028d8c1cbe",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":672,
                      "y":66},
                    "size":{
                      "width":111,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑课程/u86.png"}}]},
{
          "id":"369851aa01b44b07b128b7622c6ffa47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":40,
              "y":196},
            "size":{
              "width":1003,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f70915426dd4ab9a9a4cb61eb744c9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":40,
                  "y":196},
                "size":{
                  "width":1003,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u27.png"}},
{
          "id":"ca8771edcdfd415890ed71642300180d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":203},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78401822635e4ec6ac1e42642656d03f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66,
                  "y":203},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4949d72de9b45029ddd06fd557cd258",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":143,
              "y":203},
            "size":{
              "width":141,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b318df90c043422cb2b90d9ca5c555b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":143,
                  "y":203},
                "size":{
                  "width":141,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u31.png"}},
{
          "id":"a45645656c994d708f099cd5b7348f47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":927,
              "y":203},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dd814093ba840e4b86edeb79045ea08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":927,
                  "y":203},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u33.png"}},
{
          "id":"5e568067cc0d4904bda9f5f1774ea309",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":40,
              "y":226},
            "size":{
              "width":1003,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc6450e0ec984573a7199d9a6c8d551e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":40,
                  "y":226},
                "size":{
                  "width":1003,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u27.png"}},
{
          "id":"0b62bbc1770a49f6a7b0de71d8fba726",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":233},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5aef549d44db4ef698428d8b45eff052",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66,
                  "y":233},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5742535768a34399b45b8dc3d1baf0c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":143,
              "y":233},
            "size":{
              "width":141,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9b9b163df65472bb4bf064c92da9ed3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":143,
                  "y":233},
                "size":{
                  "width":141,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u31.png"}},
{
          "id":"e31dcf7055b243c9b85b4dd0cb6b7c7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":927,
              "y":233},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ede104b28d348e890b29f4e5676b535",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":927,
                  "y":233},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u33.png"}},
{
          "id":"d04e54333db445ceb040e10a6ab01e6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":40,
              "y":256},
            "size":{
              "width":1003,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"601fe1d15fe94e628b4216a5cee9f874",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":40,
                  "y":256},
                "size":{
                  "width":1003,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u27.png"}},
{
          "id":"21f8080d757b4f13a6cd49705d2fe2d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":263},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"592adb925f3844a9b243c9bf489cdcdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66,
                  "y":263},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d9e955085264b3086d9815aa39ecbd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":143,
              "y":263},
            "size":{
              "width":141,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68be54c526f54727b70453ececd634d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":143,
                  "y":263},
                "size":{
                  "width":141,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u31.png"}},
{
          "id":"4f63670be9fd44ce8058501d1eb316bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":927,
              "y":263},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feee1b3af153493eae5112302e7a954c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":927,
                  "y":263},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑课程/u33.png"}},
{
          "id":"3093685ac72c4a5ba4a72c95265c8891",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":40,
              "y":296},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dce4fe60d9c47ef8e0b0d2cbf3dd3ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":40,
                  "y":296},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生列表/u112.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5ac7ca50afec401283c78995e36e47a6":{
      "scriptId":"u0"},
    "4115d4a10cb5414b9925ee4f270e5f76":{
      "scriptId":"u1"},
    "b0c2f09d62994efb86a345ccbd7e141a":{
      "scriptId":"u2"},
    "187539442dfb44bd85d233039abc8ea1":{
      "scriptId":"u3"},
    "336922bb50934f6f9beb097d7b42cae6":{
      "scriptId":"u4"},
    "67ba68987f6742cf82df8c5a163a8a39":{
      "scriptId":"u5"},
    "a4949ab41e8840eda77fc9bbd7a5c4dc":{
      "scriptId":"u6"},
    "b172df1eee464f2c915c0620d2c7f626":{
      "scriptId":"u7"},
    "e255d42cc2714587a6999b987a62dc92":{
      "scriptId":"u8"},
    "efd1a6e970cc493f803edd3fd6c31970":{
      "scriptId":"u9"},
    "453d1e8a9af648758e4344d2acfb32b6":{
      "scriptId":"u10"},
    "abf436614cc74054b53554a08a8cc281":{
      "scriptId":"u11"},
    "9586b8e4af0c4df2816ca1604e21c4cd":{
      "scriptId":"u12"},
    "da66fa45f5444428bc88c0a30d0385a4":{
      "scriptId":"u13"},
    "5e0cdc9855364a05805f9b1fbfc66fc2":{
      "scriptId":"u14"},
    "e04a86639518462fb5c60a5907bf2665":{
      "scriptId":"u15"},
    "d6b9bf0b17ac4e30918635c0e937b7e7":{
      "scriptId":"u16"},
    "79362c5a25f24cc68ffd7af3e76200b8":{
      "scriptId":"u17"},
    "85d9f814c9bd47cebd7bc21eaccfd2e9":{
      "scriptId":"u18"},
    "2acc6652aa0c4732858ccb5a2469788f":{
      "scriptId":"u19"},
    "aee135b497944e4090618d33e80f5ecc":{
      "scriptId":"u20"},
    "b397eaaa11d94d71913ab0cafc4adc43":{
      "scriptId":"u21"},
    "a1d5cfa24d454b78988b07624bdf408c":{
      "scriptId":"u22"},
    "cfca8514deef4f38984ad14f33da4fc3":{
      "scriptId":"u23"},
    "4c560a25648f46089c4de78c59e7db58":{
      "scriptId":"u24"},
    "dc51b5394c3444a4ac02b9f75612feab":{
      "scriptId":"u25"},
    "196d7bb77ff2439b8bde8fec74935c26":{
      "scriptId":"u26"},
    "57c2a61cc9c34ccb937268e3eb55effc":{
      "scriptId":"u27"},
    "61149db1e31a4013b24cb1dabf608aa6":{
      "scriptId":"u28"},
    "b6d3f662f2fe46c3914e4229d623436c":{
      "scriptId":"u29"},
    "44fd638279ee46999aaa17435f07dc50":{
      "scriptId":"u30"},
    "eaf7713c54f94122af6c5a9427f97865":{
      "scriptId":"u31"},
    "928d969a07c747a69c55a3f6c2b06bbb":{
      "scriptId":"u32"},
    "f52370934d734488b61e14230176265f":{
      "scriptId":"u33"},
    "6caa7272743e4599bc7b4e810c51b7fa":{
      "scriptId":"u34"},
    "3dd326ab4778404bbb038305f2e6a5ff":{
      "scriptId":"u35"},
    "39a98ee1452a45cab8d92e570a05ec48":{
      "scriptId":"u36"},
    "3b94f606061a46d09161eb5a6b758deb":{
      "scriptId":"u37"},
    "41c2117fff584b6e8ce8f7281275e0e7":{
      "scriptId":"u38"},
    "1449e13843054a9488421f8a911d02fc":{
      "scriptId":"u39"},
    "39b0b5c609364e5cb0f31c081793be13":{
      "scriptId":"u40"},
    "82fa30b62ce54acbb2823234b53e2431":{
      "scriptId":"u41"},
    "2c72fafcf0844834ae490572d4d6c853":{
      "scriptId":"u42"},
    "0707f34f8fff43f6a736706b67c305e6":{
      "scriptId":"u43"},
    "9d54da4f33024de1ae226a6df8abd83f":{
      "scriptId":"u44"},
    "a604cb1114724370a55b8c8a6e741df6":{
      "scriptId":"u45"},
    "c9431e4624fc476bb4c3f92a65d57701":{
      "scriptId":"u46"},
    "d0844b231efd4545b619c81c5d28ca42":{
      "scriptId":"u47"},
    "0b77df7d8df54de4b3a6c778d5f5eccf":{
      "scriptId":"u48"},
    "33adbcb5923b4d89871b5e4e04327fc8":{
      "scriptId":"u49"},
    "a173b59e0c68439a94360539e9f249cc":{
      "scriptId":"u50"},
    "afb115599ffe422f9ea9c03247f9f47f":{
      "scriptId":"u51"},
    "3abdb2df59b4476ba3bb3944f64a9917":{
      "scriptId":"u52"},
    "c5e1dbd9778d41329d6a4cc7bcab45cc":{
      "scriptId":"u53"},
    "b429f0ba51f644eb8b555eb21aed4463":{
      "scriptId":"u54"},
    "11b874d1763e48788b4959b42ac27f93":{
      "scriptId":"u55"},
    "0ec8b881b9f3454d9fd941a7c74ecf82":{
      "scriptId":"u56"},
    "85859f87ac1843458417d10bc4ba9864":{
      "scriptId":"u57"},
    "0c4b24d8fdaf491ca6dcd9572d7589b3":{
      "scriptId":"u58"},
    "6989eb88966849c891aeb8856dd5149b":{
      "scriptId":"u59"},
    "56e6f4785d814326a026ae028d8c1cbe":{
      "scriptId":"u60"},
    "175ce6da00c64558826cc4374b5000b1":{
      "scriptId":"u61"},
    "bea157edd96e4226800fb706a0e75e7c":{
      "scriptId":"u62"},
    "791a9ed6e46f4b2dafd5754d95ec749c":{
      "scriptId":"u63"},
    "8aeaf66cc8c240e7a14c0203f69ee1d0":{
      "scriptId":"u64"},
    "26d1d2f6284c4c60aaeac097941beff0":{
      "scriptId":"u65"},
    "06177637686f4223bcbb1eb6754d66bf":{
      "scriptId":"u66"},
    "369851aa01b44b07b128b7622c6ffa47":{
      "scriptId":"u67"},
    "6f70915426dd4ab9a9a4cb61eb744c9e":{
      "scriptId":"u68"},
    "ca8771edcdfd415890ed71642300180d":{
      "scriptId":"u69"},
    "78401822635e4ec6ac1e42642656d03f":{
      "scriptId":"u70"},
    "e4949d72de9b45029ddd06fd557cd258":{
      "scriptId":"u71"},
    "b318df90c043422cb2b90d9ca5c555b0":{
      "scriptId":"u72"},
    "a45645656c994d708f099cd5b7348f47":{
      "scriptId":"u73"},
    "8dd814093ba840e4b86edeb79045ea08":{
      "scriptId":"u74"},
    "5e568067cc0d4904bda9f5f1774ea309":{
      "scriptId":"u75"},
    "cc6450e0ec984573a7199d9a6c8d551e":{
      "scriptId":"u76"},
    "0b62bbc1770a49f6a7b0de71d8fba726":{
      "scriptId":"u77"},
    "5aef549d44db4ef698428d8b45eff052":{
      "scriptId":"u78"},
    "5742535768a34399b45b8dc3d1baf0c0":{
      "scriptId":"u79"},
    "c9b9b163df65472bb4bf064c92da9ed3":{
      "scriptId":"u80"},
    "e31dcf7055b243c9b85b4dd0cb6b7c7f":{
      "scriptId":"u81"},
    "9ede104b28d348e890b29f4e5676b535":{
      "scriptId":"u82"},
    "d04e54333db445ceb040e10a6ab01e6c":{
      "scriptId":"u83"},
    "601fe1d15fe94e628b4216a5cee9f874":{
      "scriptId":"u84"},
    "21f8080d757b4f13a6cd49705d2fe2d8":{
      "scriptId":"u85"},
    "592adb925f3844a9b243c9bf489cdcdb":{
      "scriptId":"u86"},
    "2d9e955085264b3086d9815aa39ecbd4":{
      "scriptId":"u87"},
    "68be54c526f54727b70453ececd634d2":{
      "scriptId":"u88"},
    "4f63670be9fd44ce8058501d1eb316bf":{
      "scriptId":"u89"},
    "feee1b3af153493eae5112302e7a954c":{
      "scriptId":"u90"},
    "3093685ac72c4a5ba4a72c95265c8891":{
      "scriptId":"u91"},
    "6dce4fe60d9c47ef8e0b0d2cbf3dd3ee":{
      "scriptId":"u92"}}});